### ISSUE TITLE
Game crashes when loading up a world 

### ISSUE THREAD

**Issue by spazcore123** [DarkPacks/SevTech-Ages#4296] opened 2020-09-25 20:28 UTC
## Bug Description

 Whenever i load up a world that has 24 hours on it, my world crashes giving me a:
"The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop
Exit Code: -1" error code

### Did this behavior use to work in the previous version?

 I started playing on the current version and the version has not changed since

## Steps to Reproduce (for bugs)

1. Load up game
2. Load up world (might be clientside)
3. Game crashes (might be clientside)

## Logs

* Client/Server Log:
* Crash Log: 
[crash-2020-09-25_16.09.12-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/5285210/crash-2020-09-25_16.09.12-server.txt)

## Client Information
* Modpack Version: 3.2.0-alpha.2
* Java Version: 8.0.2510.8
* Launcher Used: Twitch
* Memory Allocated: 12 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: Yes

## World Information
* Modpack Version world created in: 3.2.0-alpha.2
* Additional Content Installed: Optifine

**Comment by sam-kirby** [comment] 2020-09-25 20:46
A new version will be out soon that fixes this - if you want to play before then please restore a backup.

Duplicate of #4256

**Closed as completed by sam-kirby** 2020-09-25 20:46 UTC
Labels: Duplicate
