### ISSUE TITLE
Age 1 Bronze/Copper sword

### ISSUE THREAD

**Issue by MrArrig** [DarkPacks/SevTech-Ages#2851] opened 2018-06-11 10:44 UTC
Currently in age 1. Copper sword has no recipe and bronze sword uses copper plates.

version: 3.0.8

**Comment by artdude543** [comment] 2018-06-11 10:46
Check closed issues before posting a new one. Ignoring the fact will result in posting permissions being disabled. The template tells you to check beforehand....

**Comment by artdude543** [comment] 2018-06-11 10:46
Duplicate of #2802

**Closed** 2018-06-11 10:46 UTC
Labels: triage
