### ISSUE TITLE
Quartz Enriched Iron  alloy operation not correctly using iron

### ISSUE THREAD

**Issue by ianken2k** [DarkPacks/SevTech-Ages#3736] opened 2019-04-20 05:55 UTC
## Bug Report
When creating quartz enriched iron in the Arc Furnace, 3 iron ingots and 1 certus quartz are required for the operation to begin, but only 1 iron ingot is used, leaving two more in the Arc Furnace.

## Expected Behaviour
All three iron ingots and the certus quartz are consumed upon the operation finishing.

## Possible Solution
Tweak the recipe.

## Steps to Reproduce (for bugs)

1. Place 3 iron ingots in a single Arc Furnace slot.
2. Place 1 certus quartz in the additives field.

## Logs

* Client/Server Log: 
[latest.log](https://github.com/DarkPacks/SevTech-Ages/files/3099798/latest.log)

* Crash Log:

## Client Information

* Modpack Version: 3.1.1
* Java Version: 10.0.2
* Launcher Used: Twitch
* Memory Allocated: 8192mb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: None

**Comment by sk2048** [comment] 2019-04-20 07:18
Duplicate of #3718

**Closed by sk2048** 2019-04-20 07:18 UTC
Labels: triage
