### ISSUE TITLE
[3.0.8] Bronze Tools Require Copper Plates to Craft

### ISSUE THREAD

**Issue by Fortain** [DarkPacks/SevTech-Ages#2952] opened 2018-06-21 07:45 UTC
## Bug Report

As of 06/21/18, if you try to craft a Bronze tool (Axe/Pickaxe/Shovel/Sword), it requires Copper Plates instead of Bronze Plates. Also, there are Copper tools listed in NEI / JEI, but no recipe for them. I think the Copper recipes were accidentally used for the Bronze ones, and the original Copper ones were deleted.

## Possible Solution

Re-enable the recipes for the Copper & Bronze tools, and double-check to make sure they're connected to the correct items.

## Steps to Reproduce (for bugs)

1. Minimum Age 1 (Bronze) Required.
2. Open NEI / JEI and select a Bronze tool.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8 (as of 06/21/18)
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Tahakk** [comment] 2018-06-21 07:55
Duplicate of #2802

**Comment by Fortain** [comment] 2018-06-21 07:58
Weird, when I searched for this a little while ago, nothing came up. <shrugs> Feel free to close and/or merge this with the previous one. Sorry. :(

**Comment by Tahakk** [comment] 2018-06-21 08:14
You can close it yourself 😉

**Closed** 2018-06-21 12:33 UTC
Labels: triage
