### ISSUE TITLE
Some Errors in My Game

### ISSUE THREAD

**Issue by ghost** [DarkPacks/SevTech-Ages#4780] opened 2023-01-12 12:08 UTC
## Bug Description

<1. I transferred this file from one computer to another several days ago. And then the first stage of the sevtech ages can use and see the items of fifth stage (when I get the item of the fifth stage, the game did not say 'unfamiliar 
 form' and let me drop it) which causes many items could not be crafted. I deleted the game 'sevtech ages' and download it again but it didn't work. (debugging with the instructions of the module is useless)
2. After that the advancements were all missed. 
3. Some blocks in the game cannot be used, such as the book of the necronamicron and the starlight blockaltar>

### Did this behavior use to work in the previous version?

<idk>

## Steps to Reproduce (for bugs)

1.I transferred this file from one computer to another, and the above problem occurred.
2./
3./

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version:<3.2.3>
* Java Version:<Java 8 (8.0.291)>>
* Launcher Used:<CurseForge, Plain Craft Launcher>
* Memory Allocated:<13.0GB>
* Server/LAN/Single Player:<Single Player>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:<3.2.3>
* Additional Content Installed:<No changes>

**Comment by sam-kirby** [comment] 2023-01-12 12:17
Duplicate of #4777 #4776 #4775 #4774 #4773 #4772 #4771 #4770 #4769 #4768

Please stop spamming.

**Closed as completed by sam-kirby** 2023-01-12 12:17 UTC
Labels: Duplicate
