### ISSUE TITLE
Water Wheels duplicate

### ISSUE THREAD

**Issue by Kalaskow** [DarkPacks/SevTech-Ages#3260] opened 2018-08-13 06:45 UTC
## Bug Report
When breaking a Water-Wheel from "Better with mods" it duplicates.

## Expected Behaviour
No duplication, just a single drop.

## Steps to Reproduce (for bugs)
1. Build Gearbox
2. Attach Wooden Axle
3. Attach Water Wheel
4. Break with Axe

## Client Information
Modpack Version: 3.0.8
Java Version: 10.0.1
Launcher Used: Twitch
Memory Allocated: 4gigs
Single Player:
Optifine Installed: no
Shaders Enabled: no

**Comment by Tahakk** [comment] 2018-08-13 07:06
Duplicate of #2971

Please use the search feature before reporting issues.

**Comment by Kalaskow** [comment] 2018-08-13 07:09
I did... Search function doesnt seem to look into closed issues ..

**Closed** 2018-08-13 08:43 UTC
Labels: triage
