### ISSUE TITLE
Duplication bug BWM waterwheel

### ISSUE THREAD

**Issue by Furionstrom** [DarkPacks/SevTech-Ages#3063] opened 2018-07-07 12:16 UTC
## Bug Report
When breaking a BWM waterwheel you get 2 back plus the axle it was on.

## Expected Behaviour
you should only get one when breaking the water wheel

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Place a BWM axle and then place the waterwheel
2. Break the waterwheel 
3. obtain multiple waterwheels 

## Client Information
* Modpack Version: 3.0.8
* Java Version:
* Launcher Used: MultiMC
* Memory Allocated: 6gb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8

## Server Information
* Java Version: Not sure about this info
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-07-07 22:29
Duplicate of #2971

**Closed by artdude543** 2018-07-07 22:29 UTC
Labels: triage
