### ISSUE TITLE
Astikoor Cart disappears/breaks when attached to a horse for travel. 

### ISSUE THREAD

**Issue by TheNubbler** [DarkPacks/SevTech-Ages#2535] opened 2018-05-19 22:25 UTC
## Issue / Bug

As the tittle indicates. Noticed it first when I first unlocked it early game and lost my cart. Didn't really have anything in it and thought it was a fluke. 

Just now I was moving to a new base, decided to try it out again. At some point the cart broke and dropped all the items on the ground. It took me a minute to find it because I didn't realize this until I reached my destination.

I was not able to recover all my items. I do not know if it was related to the bug or I just took to long. 

I was using a fast horse on mostly level terrain. 

## Expected Behavior

For it not to do the above

## Possible Solution

Go slow and periodically check behind you, no real solution

## Steps to Reproduce (for bugs)

Ride around with a fast horse.

## Context

Lost a bunch of items trying to move bases

## Client Information

Twitch launcher

Modpack version 3.0.6

**Comment by artdude543** [comment] 2018-05-19 22:45
Duplicate of #698

**Closed by artdude543** 2018-05-19 22:45 UTC
Labels: triage
