### ISSUE TITLE
Tick Loop | Crash On World load

### ISSUE THREAD

**Issue by ChosenArchitect** [DarkPacks/SevTech-Ages#4283] opened 2020-09-22 18:31 UTC
## Bug Description

 I was flying to a new island looking for chickens when suddenly my screen froze and It crashed to desktop. This time it didn't generate a crash log. So I restarted the pack and tried again. This time on world load it crashed and I was able to get a crash log. After I got the crash log I decided to removed optfine and replay mods to and get a clean crash log. It still crashed and I have the log down below. Along with the world download for more testing if interested. 
-Tried changing Forge config to removed tile issues to no prevail. Had to load a backup.

### Did this behavior use to work in the previous version?

 N/A

## Steps to Reproduce (for bugs)

1. I was just flying in Age 2 to other islands.
2. I don't know how easy this would be to replicate so I provided the world below.

## Logs

* Client/Server Log: https://pastebin.pl/view/e50d675e
* Crash Log: https://pastebin.pl/view/31eeee33
* World Download: [Google Drive Link](https://drive.google.com/file/d/1dlmnxI89uwXS4K9hamlzI9X-_CtZSz8V/view?usp=sharing)

## Client Information
* Modpack Version: 3.20-alppha.2-skyblock
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.20-alppha.2-skyblock
* Additional Content Installed: No

**Comment by sam-kirby** [comment] 2020-09-22 19:07
Duplicate of #4256

**Closed as completed by sam-kirby** 2020-09-22 19:07 UTC
Labels: Duplicate
