### ISSUE TITLE
Twilight Forest Portal Derps

### ISSUE THREAD

**Issue by KikiCur** [DarkPacks/SevTech-Ages#2626] opened 2018-05-25 15:29 UTC
I'd like to suggest finding an alternate item to the starmetal ingot (or a TF equivalent way to get one) once you enter twilight forest such that if someone gets stuck they can reopen a TF portal from the TF side without having to cheat or have a server admin come rescue them.

I timed out on a server and my portal did not form properly as it was set in the middle of an innaccessible region because of progression.
Another person had his portal on the TF side get destroyed by a creeper.

In both cases we had no easy access back to the overworld, no access to shoggoths and the start of Abyssal craft and consequently no way to make an astral starter table to make the star metal ingot legitimately.

Our only option is to cheat or be rescued if playing with other people.

Thank you for your time.

**Comment by vadis365** [comment] 2018-05-25 15:56
better

**Comment by KikiCur** [comment] 2018-05-25 17:02
you're right on the shoggoth lairs in swamps Vadis, I just found one beside my second labyrinth entrance (still hunting for the charms of keeping)

**Comment by Gameswithjohn** [comment] 2018-05-25 19:01
I've seen a few in the swamp biomes. Actually a good way to get the shoggoths instead of hunting them down in the overworld. But the block breaking acid is a pain in the ass for many things, including portals.

**Comment by artdude543** [comment] 2018-05-25 23:31
I don't personally consider this a bug at **all**. In my opinion, this is a Vanilla based mechanic. _You want us to change how to light a portal in the Nether when a Ghast destroys it, no? You'll be stuck there forever unless you manage to get a fire thrown at it._

Like these things **will happen** even changing to another item you'll still have the similar issue. Diamond won't be used again for this. And then we'd need to find an item which is high tiered and then still available in the TF.

I'm totally fine with the need for cheating on this one. It's a rare thing to happen anyway. TF are aware of some rare case spawning issues and if you blow up, then I guess bad luck? A smart move would be to have a chest nearby with spare ingots in the situation of a blowup. Like at the end of the day it's an RNG issue. You're still able to get the AS stage in the TF when you find the Shoggoths sure it can be hard. But we can't keep changing the mechanics for the pack when something as small as this comes up. The pack will start to lose its feel.

All of the aspects of making the Ingot are there in the TF so technically your not actually _stuck_ you just have to start again. Like even in Vanilla TF I'd take spare Diamonds for this very reason.

**Comment by vadis365** [comment] 2018-05-26 13:52
It's bad game design to not cover these things when they occur, sure players can start all over and spend hours re-tracing all their progress and create duplicate redundancy, but honestly, people wont.
I agree it is a rare thing to happen and as such can be ignored if it's a hassle to simply patch with a high tier item from within TF. Cheating in the item is the best way to solve it, and would probably be what anyone does. Ghasts cannot destroy obsidian and can also relight a nether portal with their fireballs, I don't see a parallel as most times a Nether death will result in an OW spawn, in this particular case you are stuck IN the TF dimension. As for the 'changing the feel of the pack', I think that is just a an invented soundbite to attempt to add some gravitas to your argument. The pack has evolved and changed constantly from it's inception to where it is now. The past few months and hard work the scripting team have put in some huge fixes and changes (props to you btw :) ) but each iteration of updates and bug fixes has changed things for the better. If you don't want to fix the issue, just close it. It's still a bug.

**Comment by justinrusso** [comment] 2018-05-28 23:07
> All of the aspects of making the Ingot are there in the TF so technically your not actually stuck you just have to start again. Like even in Vanilla TF I'd take spare Diamonds for this very reason.

Based on this information, this is not an issue anymore. If you can obtain everything and get the item to go back, I don't see what the issue is. Be prepared and bring a second if you are that concerned.

**Closed by justinrusso** 2018-05-28 23:07 UTC
Labels: Invalid

**Comment by vadis365** [comment] 2018-05-29 17:43
Why would you need to take spare diamonds to the Twilight Forest? Diamonds generate there fine in it's 'vanilla state'. I have discussed this with Darkosto and we have asked the TF team if it's either already possible, or can be added, to add more than 1 item to the portal gen. Making a portal to the hunting dimension is actually the best solution to dimension hop as it is made from wood and easily obtained in TF. The issue IS NOT invalid and as such has been addressed now.

**Comment by justinrusso** [comment] 2018-05-29 17:45
>we have asked

? https://github.com/TeamTwilight/twilightforest/issues/535 I asked.

I spoke to darkosto and formed my response based on his reply. Further discussion brought the idea of supporting multiple items, and thus I reported the request on the issue tracker and will be added when they do add.
