### ISSUE TITLE
Bronze Tools are made using Copper Plates

### ISSUE THREAD

**Issue by Synoxys** [DarkPacks/SevTech-Ages#2878] opened 2018-06-14 02:18 UTC
## Bug Report

When viewing the recipe for bronze tools from the Pickle Tweaks mod, NEI indicates that copper plates are required to craft them. This recipe does work, and produces the bronze tools.

## Expected Behaviour

The copper plates are supposed to be bronze plates because the tools are made of bronze, not copper.

## Possible Solution

Seems like a simple enough recipe change.

## Steps to Reproduce (for bugs)

1. Craft a Bronze Pickaxe (or any other bronze tool from the Pickle Tweaks mod) according to the NEI recipe.
2. Observe that copper plates are used instead of bronze.

## Logs

* Client Log: https://paste.atlauncher.com/view/251061cc 
* Server Log: https://gist.github.com/Synoxys/1d904bba46fbd3ca63c09b8c07d884a5
* Crash Log: No Crash

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_171-b11
* Launcher Used: ATLauncher
* Memory Allocated: 4096mb
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: None

## Server Information
* Java Version: 1.8.0_171-b11
* Operating System: Windows 10
* Hoster/Hosting Solution: A friend of mine's PC.
* Sponge (Non-Vanilla Forge) Server:

**Comment by justinrusso** [comment] 2018-06-14 02:39
Duplicate of #2802

**Closed by justinrusso** 2018-06-14 02:39 UTC
Labels: Duplicate
