### ISSUE TITLE
Skyhook + hv wire = OOoooff (crash)

### ISSUE THREAD

**Issue by GamerCoke** [DarkPacks/SevTech-Ages#3821] opened 2019-06-27 22:06 UTC
## Bug Report

tried to use a skyhook (holding right click to mount) and went to touch the hv wire, and crashed

## Expected Behaviour

either getting zapped by hv wire, or mounting the hv wire with the skyhook

## Possible Solution

I'm not sure how the coding works, but possibly damage the skyhook, or break it, when getting into contact with live wires? this might need an update, to make the skyhook a 'tool variant'(?I might be stupid, idk?) to give it damage values

## Steps to Reproduce (for bugs)

1. place hv wire vertically
2. power hv wire (I used 8 windmills with full wind catching cloth thing, and 8 3-stacked watermills (aka. 3 watersmills on each of 8 kinetic generator blocks))
3. try to ride the hv wire with the skyhook (hold right click) and approach, you should crash at touch

## Logs

* Client/Server Log: [2019-06-27-1.log](https://pastebin.com/d7HyzLeT) other log is... 2.7 megs...
* Crash Log: [crash log ](https://pastebin.com/QvDbn8Td)

## Client Information

* Modpack Version: 3.0.8
* Java Version: Java 8 update 211
* Launcher Used: Twitch Launcher
* Memory Allocated: 12288 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: default
* Shaders Enabled: default

## World Information

* Modpack Version world created in: 3.0.0

* Additional Content Installed: none

**Comment by sk2048** [comment] 2019-07-09 15:28
Can't reproduce this in the test version of the pack so it may already have been fixed by Immersive Engineering. Please reopen if you continue to experience this in newer versions.

**Closed by sk2048** 2019-07-09 15:28 UTC
Labels: Category: Mod, Investigate Further, Status: Cannot Reproduce, Type: Crash, Version: Outdated
