### ISSUE TITLE
Silicon essence useless

### ISSUE THREAD

**Issue by voltz20** [DarkPacks/SevTech-Ages#4085] opened 2020-04-10 17:37 UTC
Silicon essence doesn't work to craft silicon as there is no recipe for it. Because of this there is no way to get more silicon. 

## Bug Report
No recipe for silicon in mystical agriculture in 3.1.2
add a recipe for silicon in mystical agriculture in 3.1.2
## Expected Behaviour
Expected behavior: I put silicon essence in the crafting table, and it comes out as silicon
The change should let me craft silicon

## Possible Solution
Add a recipe for silicon

## Steps to Reproduce (for bugs)
1. get to age 5
2. make silicon seeds
3. try to craft silicon

**Comment by sam-kirby** [comment] 2020-04-11 00:59
Duplicate of #3913

**Closed by sam-kirby** 2020-04-11 00:59 UTC
Labels: triage
