### ISSUE TITLE
Bronze shield not craftable/duping liquid bronze

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#3815] opened 2019-06-22 17:59 UTC
## Bug Report
https://gfycat.com/lonelyphonyegg
https://gfycat.com/constantblackimperialeagle
The liquid bronze "pours" out onto the casting table, but only 6 mbs when it's suppose to be 4 ingots.  But really, it stays inside just invisible until it's updated.

## Expected Behaviour
The liquid shouldn't dupe and I should be able to pour out 4 ingots worth of bronze onto the shield instead of 6 mbs to make the bronze shield.

## Possible Solution
Fix it dakroA

## Steps to Reproduce (for bugs)

1. Just follow the video Krappa
2.

## Logs

* Client/Server Log: No logs made
* Crash Log:

## Client Information

* Modpack Version: 3.1.1
* Java Version: Latest
* Launcher Used: Twitch
* Memory Allocated: 8
* Server/LAN/Single Player: SP
* Optifine Installed: Y
* Shaders Enabled: N

## World Information

* Modpack Version world created in: 311

* Additional Content Installed: none

**Comment by sk2048** [comment] 2019-06-22 21:49
Fixed in 3.1.2, duplicate of #3650

**Closed by sk2048** 2019-06-22 21:49 UTC
Labels: triage

**Comment by sk2048** [comment] 2019-06-22 21:50
Also, the fluid isn't duped, on the server (thread) the fluid never goes into the casting table.

**Comment by JackRuby1** [comment] 2019-06-23 01:10
I searched too darkoHmm
I was able to pour the liquid out of the casting table into a tank though?
