### ISSUE TITLE
[Suggestion] Adding Betweenlands Life Crystal to loot table

### ISSUE THREAD

**Issue by Gameswithjohn** [DarkPacks/SevTech-Ages#2691] opened 2018-05-30 20:00 UTC
Just a thought that adding Life Crystals to the loot drop chances for chests and/or pots in the Betweenlands might be helpful for that area.

And just because, the "jam" in a donut is kinda fruit, would be great having that added as part of the fruit food list.

**Comment by monodemono** [comment] 2018-06-03 09:09
I disagree with adding the life crystal to any loot tables. As it is, it works as designed within the mod, and more importantly, it's not required to progress between stages. So you have the decision of doing extra work to complete the Betweenlands for your own enjoyment and/or benefit, or just playing through the pack.

Fruit should definitely be added as a nutrition category for the jam donut though. The mod already handles balancing for having multiple nutrition types in a single food, so it wouldn't even need to be altered beyond that.

**Comment by WorldWarHulk** [comment] 2018-06-03 10:37
yeah though odd that there was on fruit for the jam donut even 1% would be nice as it just seem stupid, to make it as you use pears and they give 4% fruit I think.
Also Life crystals from bosses or harder enemies would be nice as it drops the Grind.
I just cheat them in myself as only got one in a 3000 block search.

**Comment by Gameswithjohn** [comment] 2018-06-04 00:03
The jam donut idea was just a side thought since you can kinda just bring in other foods (unless that's a glitch on my side where the food doesn't rot in my backpack), but nice none the less just in case and eating all the different food types is a neat mechanic that is harder to use in the Betweenlands until the later parts of that pack.

As for the life crystals, yeah it was more about reducing the grind a little, especially since the Betweenlands isn't the focus of the pack, but more a side area. There are already plenty of other things that take lots of time to possibly find (such as the Astral sorcery items that only spawn in the beneath, or trekking to find darklands, etc. It wasn't asking for an added % for that one ring you need for journey map, just something to slightly speed up some of the other betweenlands items a little since that place is already slow enough just walking through it.

**Comment by artdude543** [comment] 2018-06-04 11:33
Life Crystal _won't_ be added to the loot table. It works as intended with the mod. If they want it to add on their side that's on the mod. But in terms of us, it's staying as the intentions from the mod maker.

The donut will be fixed for the nutrition values.

**Closed by artdude543** 2018-06-04 11:33 UTC
Labels: triage
