### ISSUE TITLE
Drying Racks don't work

### ISSUE THREAD

**Issue by JavierRC22** [DarkPacks/SevTech-Ages#4092] opened 2020-04-20 04:07 UTC
I'm starting a world and i'm trying to get leather, but the drying raks don't function, i tryed the first step that is put the salted hide but nothing happens. I waited for 15 minutes approx and i can't advance with the challenges.

**Comment by sam-kirby** [comment] 2020-04-20 11:30
Drying Racks work for me. Check you haven't accidentally crafted "Item Racks", which look the same and have a similar recipe but are for displaying items only.

**Comment by sam-kirby** [comment] 2020-05-02 23:59
Closing due to inability to reproduce and silence form issue creator.

**Closed by sam-kirby** 2020-05-02 23:59 UTC
Labels: Status: Cannot Reproduce
