### ISSUE TITLE
weedwood rowboat causes water to be invisible

### ISSUE THREAD

**Issue by Seamonster778778778788** [DarkPacks/SevTech-Ages#3141] opened 2018-07-20 02:35 UTC
## Bug Report

While on a weedwood rowboat, the water is invisible
## Expected Behaviour

Not invisible water
## Steps to Reproduce (for bugs)

1. Get a weedwood rowboat
2. place

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Latest
* Java Version: Latest
* Launcher Used: Native
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server 
* Optifine Installed: No
* Shaders Enabled: No

![image](https://user-images.githubusercontent.com/34897864/42980151-a5cc991a-8b9b-11e8-8938-119ba66dc905.png)

**Comment by artdude543** [comment] 2018-07-20 12:32
Fixed in the next update of the mod.

**Comment by artdude543** [comment] 2018-07-20 12:32
Duplicate of #2506

**Closed by artdude543** 2018-07-20 12:32 UTC
Labels: triage
