### ISSUE TITLE
Crafting Bronze Tools from copper plates. (Recipie Bug)

### ISSUE THREAD

**Issue by IgnisFlamme** [DarkPacks/SevTech-Ages#2934] opened 2018-06-20 13:03 UTC
## Bug Report
Conflicting recipes for Copper Tools (Pick, shovel sword) and Bronze Tools (both from mod Pickle Tweaks).

## Expected Behaviour
I'm going to use a pickaxe as an example here. They both use copper plates for crafting. When attempting to craft with copper plates (from mod Immersive Engineering), a bronze pickaxe is created instead of a copper pickaxe. 

## Possible Solution
Fix the recipie to use copper plates for copper pickaxe and bronze plates for bronze pickaxe. (and all the other tools)

## Steps to Reproduce (for bugs)
1. Make sure the Age is set to 1 (Age:1)
1. Craft a copper pickaxe with sticks and copper plates (Immersive Engineering) 
2. Find out that the result is not a copper pickaxe but a bronze pickaxe (Not that I'm complaining)

## Logs
No need for a log. (-_-)

## Client Information
* Modpack Version: 3.0.8 (Jun 8)
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.7
* Additional Content Installed: None

**Comment by Stifling-Bossness** [comment] 2018-06-20 13:39
Duplicate of #2802

**Closed** 2018-06-20 19:38 UTC
Labels: triage
