### ISSUE TITLE
Crash while initalizing game (step 3/7)

### ISSUE THREAD

**Issue by BananaTassium** [DarkPacks/SevTech-Ages#3279] opened 2018-08-16 17:40 UTC
## Bug Report
While loading Sevtech the game keeps crashing. I tried loading multiple times and it consistently crashes while in step 3/7 (initializing minecraft engine) and 5/5 (loading entity renderer).

## Expected Behaviour
The game crashes, when in the past it has loaded fine. I've never had this problem before and I'm in semi-early creative age, so I've had a lot of time for it to show up before. I've been up to date since 3.0.8 came out, and I closed the game just like normal but this time it just decided to crash.

## Possible Solution
No idea. I tried uninstalling Sevtech and copying over the important bits (saves, config, stuff like that) but it still had the same problem, seemingly.

## Steps to Reproduce (for bugs)
1. 
2. 

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/tFfnBt3C

## Client Information
* Modpack Version: 3.0.8
* Java Version: 1.8.0_51 (I think?)
* Launcher Used: Native
* Memory Allocated: 8192
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: I think 3.0.5..? Around then, at least.
* Additional Content Installed: N/A

**Comment by artdude543** [comment] 2018-08-16 17:40
Duplicate of #3271

**Closed by artdude543** 2018-08-16 17:40 UTC
Labels: triage
