### ISSUE TITLE
Cut natura wood with saw

### ISSUE THREAD

**Issue by sykefu** [DarkPacks/SevTech-Ages#2718] opened 2018-06-02 07:56 UTC
## Context
It seems strange that only natura wood can't be cut by the saw from better with mods

## Config/Script Details
* Link:
no idea how to do that

## Mod Details
* Name: Better with mods
* CurseForge Link: https://minecraft.curseforge.com/projects/better-with-mods

**Comment by artdude543** [comment] 2018-06-02 10:29
Duplicate of #2369

**Closed by artdude543** 2018-06-02 10:29 UTC
Labels: triage
