### ISSUE TITLE
IE press duplication issue

### ISSUE THREAD

**Issue by justdiver** [DarkPacks/SevTech-Ages#3883] opened 2019-08-12 16:47 UTC
Beta - 3.1.2 HF1

Using the IE metal press with the packing 3x3 mold, you can put 10 ingots on the belt  (I only tested steel and iron but I'm assuming this will probably work with all ingots) and it will output 2 blocks and 1 ingot, effectively turning 10 ingots into 19 ingots.  You can repeat this process indefinitely.

**Comment by sk2048** [comment] 2019-08-12 17:05
Duplicate of #3732

**Closed by sk2048** 2019-08-12 17:05 UTC
Labels: Duplicate
