### ISSUE TITLE
Rustic Booze Crafting Recipe to Glass Bottle Unavailable

### ISSUE THREAD

**Issue by MacDeth** [DarkPacks/SevTech-Ages#3166] opened 2018-07-24 04:21 UTC
## Bug Report

When placing a bottle of any Rustic mod booze in a crafting table, the player cannot get a normal glass bottle back.

## Expected Behaviour
The [Rustic Almanac mentions](https://puu.sh/B1VQg/d50bbca85a.png) the player being able to put a booze bottle in a crafting table to get a normal glass bottle back, as a convenience.
## Possible Solution

Somehow fix/implement the recipe.

## Steps to Reproduce (for bugs)

1. Get any bottle of Rustic mod booze.
2. Place it in a crafting grid.
3. Observe that you cannot get a glass bottle out of it.

## Client Information

* Modpack Version: 3.0.8
* Java Version: 
* Launcher Used: Twitch
* Memory Allocated: 12,288 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System: Windows
* Hoster/Hosting Solution: On a friend's personal computer
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-07-24 11:46
Duplicate of #2157

**Closed by artdude543** 2018-07-24 11:46 UTC
Labels: triage

**Comment by MacDeth** [comment] 2018-07-24 15:51
Apologies, I did try to look for this issue before I posted. I couldn't find it though.
