### ISSUE TITLE
Crashing Often

### ISSUE THREAD

**Issue by TheMiningGinger** [DarkPacks/SevTech-Ages#4277] opened 2020-09-21 00:01 UTC
## Bug Description
I am having issues all around with this modpack. When I try to load in it is laggy and only occasionally loads. The game consistently crashed on my last reset of Sev, and it is laggy on world loadup and in general.

### Did this behavior use to work in the previous version?
I cannot recall if there were any version changes causing issues. If anything the 3.1.7 update.

## Steps to Reproduce (for bugs)
1.Load the Modpack.
2.If step one doesn't fail, play and get into game.
3.If step two doesn't fail, play until crash.
Side note: Crashing is consistent.

## Logs
[cbbbbfbb.txt](https://github.com/DarkPacks/SevTech-Ages/files/5252901/cbbbbfbb.txt)

* Client/Server Log: https://pastebin.pl/view/raw/cbbbbfbb

## Client Information
* Modpack Version:<1.12.2>
* Java Version:<1.8.0_51>
* Launcher Used:<Twitch>
* Memory Allocated:<8GB-11.520GB>
* Server/LAN/Single Player:<Singleplayer>
* Optifine Installed:<No>
* Shaders Enabled:<No>

## World Information
* Modpack Version world created in:<1.12.2>
* Additional Content Installed:<None>

**Comment by sam-kirby** [comment] 2020-09-21 04:48
The crash you're having points to a bad configuration file; I'm not seeing this issue, and noone has reported it. Have you made any edits? If not, try reinstalling the pack. Which launcher are you using to install the pack?

**Comment by TheMiningGinger** [comment] 2020-09-21 12:43
@sam-kirby  Thanks for the quick  response time. I believe I messed with the files while trying to optimize it because it was crashing before I messed with the files. That being said, I think I tried to halt better_foliage on a previous attempt at loading it. After that, I reinstalled it and it worked quite well and then crashed like usual and now won't let me in. I'm using the Twitch/Curseforge Launcher. I am also using the "Native Launcher" option on Twitch instead of the "Jar Launcher". How may I undo this damage?

**Comment by Darkosto** [comment] 2020-09-21 18:29
There's a couple things I noticed while looking at your logs:

1. You're dedicating 10gb of RAM? This is honestly too much in this environment. You should not need to dedicate more than 6gb-8gb of RAM. I would suggest that if you have enough in your system to set your min/max RAM allocation to 6gb-6gb or 8gb-8gb. Unless you're running an intensive resource pack or shaders, assigning more will not be helpful and can actually cause more trouble. Especially during garbage collection which will lock your game up for longer since it has more memory to dump from assigning too much RAM.
2. I would consider updating your Java to a newer Java 8 version. It wouldn't necessarily fix your crashes, but newer Java versions do have performance fixes and security updates which can be helpful. 
3. Use the following arguments in your launcher to get a bit better performance: 

When assigning 6GB:
```
-Xmx6g -Xms6g -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

When assigning 8GB:
```
-Xmx8g -Xms8g -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

4. After doing the previous steps, if you're still having trouble I would reinstall the pack and see if it's a bad install.

**Comment by TheMiningGinger** [comment] 2020-09-22 01:55
@Darkosto Although I'm now able to get back into the game after using 8GB, your arguements in the launcher, and resetting the pack, it is still extremely unstable and laggy. This has only reverted it to the issue before I messed up the arguements while trying to fix this very lag. I have no reason why it would be on my end, but it's still possible. Thanks for your time

Update: Constant freezframing is more specifically an issue I'm having. The screen will completely stop for varyingly long intervals, commonly being around 20 seconds. While this is happening, the server continues to move. I just died to a pack of wolves who broke my armor and then my face :(

Update # 2: It has become completely unplayable again. I love this modpack and would love to pass the 1st age :). I will try whatever I can to make it work, but until then. Sayonara Sevtech :(

**Comment by sam-kirby** [comment] 2020-09-22 08:04
Can you share details of the hardware you're having trouble on?

**Comment by TheMiningGinger** [comment] 2020-09-22 12:43
@sam-kirby 
CPU: AMD Ryzen 3 1200 Quad-Core Processor
RAM: 16GB RAM (8 allocated, thanks to Dark)
Graphics: NVIDEA GeForce GTX 1050

Ps: I've heard that Better Foliage can be an issue for AMD Ryzen users? I don't know if that's true, just informing you.

Edit: I also have accidentally reopened and closed this a couple of times. Clumsy of me

**Comment by TheMiningGinger** [comment] 2020-09-23 15:32
@Darkosto

**Comment by TheMiningGinger** [comment] 2020-09-23 17:10
@sam-kirby @Darkosto 
If there are any other details I can give, fire away.

**Comment by TheMiningGinger** [comment] 2020-09-25 22:55
Sorry for the bother @sam-kirby and @Darkosto , but is this thread dead? It's been days since the last response and I'm thinking it's dead. If you're busy, obviously don't worry, just wondering.

**Comment by sam-kirby** [comment] 2020-09-25 23:12
I don't really have anything to go on - I run the pack on a Ryzen based system and I've not had issues.

You can remove better foliage, as well as fancy block particles and smooth font to improve performance without issue, and you should try this if you haven't already.

Further, you haven't given us a crash report that wasn't caused by changes made by you. Could you provide an example of a crash you are experiencing in a fresh install of the pack (after removing the above listed mods, if you wish)?

**Comment by TheMiningGinger** [comment] 2020-09-25 23:24
Yes, thanks. I'll try removing them. How would I go about removing them safely? If I get a crash report I'll report it here.

**Comment by Darkosto** [comment] 2020-09-25 23:37
Also, could please check your RAM speed? I'm just trying to get a system profile to help figure out what's going on

**Comment by TheMiningGinger** [comment] 2020-09-25 23:52
1067MHz is the DRAM frequency, I think this is what you asked. If not I'll fix

**Comment by TheMiningGinger** [comment] 2020-10-02 12:51
Is there a safe way of removing the previously mentioned Better Foliage? Also if there is any other info I can give on this let me know, but it is annoying that no one else has had this issue :( Thanks for your time

**Comment by sam-kirby** [comment] 2020-10-02 15:34
You can turn better foliage off in game through its config menu, or just delete the mod's jar file. There isn't really an unsafe way to do it.

**Closed as completed** 2021-02-19 04:55 UTC
Labels: Status: Needs more Information, Status: Cannot Reproduce, Category: Performance
