### ISSUE TITLE
piston bug

### ISSUE THREAD

**Issue by metroidboy** [DarkPacks/SevTech-Ages#3999] opened 2019-11-30 16:30 UTC
## Bug Report
 cant craft pistons with wireles grid

## Steps to Reproduce (for bugs)

1. have working refined storage system
2. use a wireless crafting grid 
3. go to JEI and find pistons and shift click to craft them
4. the game crashes and it closes the server nad have to re open the word 

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version:latest
* Launcher Used: twitch
* Memory Allocated:8 gb
* Server/LAN/Single Player: sp
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version: latest
* Operating System:Windows 10
* Hoster/Hosting Solution:none
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment] 2019-11-30 17:39
Duplicate of #2498

**Closed by sam-kirby** 2019-11-30 17:39 UTC
Labels: triage
