### ISSUE TITLE
AE2 Fluid storage support (Extra Cells)

### ISSUE THREAD

**Issue by MaucnAD** [DarkPacks/SevTech-Ages#3330] opened 2018-08-26 20:54 UTC
Since refined storage has fluid storage built into the mod, I feel Extra cells should be added for AE2 fluid support. It does need some recipe changes most likely so that it is a little balanced around the pack. 
It should be accesible at the same time Refined Storage is (Age 5).

I understand I can use Refined storage, but I dont like using both of the mods, and I like AE2 more. RS is just a way easier AE2

* Name: Extra cells 2

* CurseForge Link:
https://minecraft.curseforge.com/projects/extracells2

**Comment by MaucnAD** [comment] 2018-08-26 21:07
Oh, and maybe wireless crafting monitor for AE2 as well? 

https://minecraft.curseforge.com/projects/wireless-crafting-terminal

**Comment by artdude543** [comment] 2018-08-26 22:00
Duplicate of #1042

**Closed by artdude543** 2018-08-26 22:00 UTC
Labels: triage
