### ISSUE TITLE
Internal Server Crash

### ISSUE THREAD

**Issue by eatpete** [DarkPacks/SevTech-Ages#3139] opened 2018-07-19 23:30 UTC
## Bug Report

the bug appears to have happen before with #1989 and my problem seems be very similar if not Identical to #1989's problem. The problem is when I enter a different dimension it goes fine but when I leave the dimension to go back to the overworld I enter the overworld nothing is rendered and it goes to loading screen with the words shutting down internal server. 

## Expected Behaviour

it puts me in the overworld then turns to a loading screen saying shutting down internal server.

## Possible Solution

I found a temporary fix where I just hit the repair Minecraft button (since I'm on the twitch launcher)

## Steps to Reproduce (for bugs)

1. enter world
2. wait a couple seconds
3. crashes

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/eatpete/7adfe68660441fad77b9e32992102eec

## Client Information

* Modpack Version: 3.08
* Java Version: 1.8.0.171
* Launcher Used: twitch
* Memory Allocated: 3,584
* Server/LAN/Single Player: single
* Optifine Installed: no 
* Shaders Enabled: yes

## World Information

* Modpack Version world created in: 3.08

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-07-20 12:31
Well according to your logs

```
[15:17:32] [Server thread/INFO] [FML]: The game window is being closed by the player, exiting.
[15:17:32] [Server thread/WARN] [FML]: Java has been asked to exit (code 0)
[15:17:32] [Server thread/WARN] [FML]: Exit trace:
[15:17:32] [Server thread/WARN] [FML]: 	net.minecraftforge.fml.common.LoadController.transition(LoadController.java:144)
[15:17:32] [Server thread/WARN] [FML]: 	net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:795)
[15:17:32] [Server thread/WARN] [FML]: 	net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:296)
[15:17:32] [Server thread/WARN] [FML]: 	net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:158)
[15:17:32] [Server thread/WARN] [FML]: 	net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[15:17:32] [Server thread/WARN] [FML]: 	java.lang.Thread.run(Thread.java:748)
[15:17:32] [Client Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```
You closed the game. _Note: This is never logged unless the user actually clicks the exit button_ So don't say you did not cos I know how that line of code works 💻 

Regardless the issue was fixed in a small number of mods. But this is an issue for some players due to the pack being a resource hog _(which is intended)_ and some systems just can't handle the pack or the network traffic it's throwing around. We have a major update coming soon, which the mods which handle syncing of stages is changed a bit. Along with some major mods having some cleanups. So it _could_ be helped in that regards. But apart from mods handing their network better or big mods playing better with each other. There is nothing we can do. The pack was designed specifically for one person's system. It's a massive pack which requires the hardware to make it work w/o hitting random crashes here or there. Which 99% are caused by slow systems.

You can try messing with Java Args or adding more RAM or wait for the next update (which has no eta) to see if that helps.

Thanks for your issue tho!

**Closed by artdude543** 2018-07-20 12:31 UTC
Labels: triage
