### ISSUE TITLE
BTM Saw doesn't cut Yew logs but JEI says it should

### ISSUE THREAD

**Issue by ickus** [DarkPacks/SevTech-Ages#2632] opened 2018-05-25 23:46 UTC
## Bug Report
JEI lists yew logs being able to be cut by the saw but placing a yew log in front of the saw does not do this.

## Expected Behaviour
Nothing happens.  The saw does not cut the log.

## Steps to Reproduce (for bugs)
1. Place yew log in front of a running better than mods saw.
2. Watch as yew log is not sawed.

## Logs
No crash log because the issue doesn't cause a crash.
* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Memory Allocated: 8175 MB
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by TheMingo888** [comment] 2018-05-25 23:51
Duplicate of #2369.

**Closed** 2018-05-25 23:56 UTC
Labels: Duplicate
