### ISSUE TITLE
Modpack disables itself when removing client mods, or any mods, from the server.

### ISSUE THREAD

**Issue by Zilacon** [DarkPacks/SevTech-Ages#4695] opened 2022-03-26 01:09 UTC
## Bug Description
All custom recipes, ages, advancements, etc do not work on server when ANY mod is removed from the pack.
This includes CLIENT MODS which should not be in the SERVER.

### Did this behavior use to work in the previous version?
2.3.2 is the first version we have tried to setup a server for.

## Steps to Reproduce (for bugs)
1. Drag and drop all server files into server.
2. Remove client mods from server mods folder.
3. Start server.
4. Find everything that makes the pack, disabled or non functional when joining the server.

## Logs
* Client/Server Log: [latest.log](https://github.com/DarkPacks/SevTech-Ages/files/8354430/latest.log)

## Client Information
* Modpack Version: 2.3.2
* Java Version: Oracle Java 8 build 311
* Launcher Used: Curse
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 2.3.2
* Additional Content Installed: None

## Server Information
* Java Version: AdoptJDK OpenJ9 Java 8
* Operating System: Linux Lubuntu 20.04
* Hoster/Hosting Solution: Independently Hosted on Dedicated Server
* Sponge (Non-Vanilla Forge) Server: Hybrid Server (Bukkit/Forge)

**Comment by sam-kirby** [comment] 2022-03-26 01:43
Changing the pack carries a risk of breaking the pack. Everything is quite tightly interwoven so SevTech is especially sensitive to change.

That being said, client mods can be removed - they are not loaded on the server. You can remove, for example, Fancy Block Particles, Smooth Font, Better Foliage and others without issue. There are probably more but I can't think of them off the top of my head.

What client only mods in particular are you having issue with?

**Comment by Zilacon** [comment] 2022-03-26 01:47
When my server starts it gives a long list of mods to remove because they are client mods.
When we remove these mods, joining the server shows everything to be broken.
Ages dont work, advancements dont work, custom recipes dont work, everything is defaulting to vanilla recipes and advancements.

At first we thought it was because i removed RFTools and Streams, so i added those back and the problems still persisted.
My staff then did testing of their own and found that if you removed ANY MOD from the pack, no matter what it is, the modpack is forever broken unless that world is wiped and the removed mod added back in to regenerate the world.

**Comment by sam-kirby** [comment] 2022-03-26 01:49
Neither of the mods mentioned are client only. Streams is worldgen - needless to say this is done on the server, RFTools adds blocks and items which necessitates being installed on the server. What line in the log tells you to remove these mods?

**Comment by Zilacon** [comment] 2022-03-26 01:54
Its like you skim through my messages, and dont read everything ive typed. You closed my last issue when i stated it was a problem that ive encountered in the past and can be fixed by the mod.

I clearly stated the removal of rftools or streams did not have an affect on resolving the problem. The problem persists even if any mod is removed. As for why those 2 mods were removed, they are a performance problem for servers.

**Comment by sam-kirby** [comment] 2022-03-26 01:59
I'm skimming because it's 2am and I'd like to go to bed but I'm trying to help you anyway.

> When my server starts it gives a long list of mods to remove because they are client mods.

Okay - provide this list.

**Comment by sam-kirby** [comment] 2022-03-26 20:35
I'm going to close this as as it's entirely predictable behaviour that removing mods may cause script errors.

Removing client mods from the server should not cause any issue as the server will not load a client mod; whatever mods you have removed must be loaded by the server for removing them to have an effect therefore they are not client mods.

There is no system in place that is detecting pack changes and "disabling" anything. What is most likely happening is you removed a mod that is referenced in a script, causing an error and halting script loading. It is up to you to resolve any errors caused by your modification.

**Closed as completed by sam-kirby** 2022-03-26 20:35 UTC
Labels: Env: Server
