### ISSUE TITLE
Dropping Etching Acid on Nether Warts turns them into beetroot (don't ask.)

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2782] opened 2018-06-07 17:10 UTC
## Bug Report
Dropping Etching Acid from PneumaticCraft on a Nether Wart farm (NetherEx Tilled Soulsand with Nether Wart Crops on it (that are fully grown) drops Beetroot and Beetroot Seeds

## Expected Behaviour

Ideally, clearing a Nether Wart farm with a liquid would drop Nether Warts.

## Possible Solution
IDHAFC

## Steps to Reproduce (for bugs)

1. Progress in PneumaticCraft
2. Have your Nether Wart farm right below your Etching Acid pool
3. Decide to "redesign" the area
4. Have Etching Acid kill your pets and flood your farming area

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_161 64bit
* Launcher Used: Twitch App
* Memory Allocated: 6400MB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: nada

## Server Information
* Java Version: -
* Operating System: -
* Hoster/Hosting Solution: -
* Sponge (Non-Vanilla Forge) Server: no

**Comment by artdude543** [comment] 2018-06-07 17:42
Caused by #1274 which is fixed in 3.0.8 :)

**Closed by artdude543** 2018-06-07 17:42 UTC
Labels: triage
