### ISSUE TITLE
Twilight Forest Ur-Ghast Tower/random Structures Issue

### ISSUE THREAD

**Issue by Phantum** [DarkPacks/SevTech-Ages#1722] opened 2018-04-11 07:54 UTC
## Issue / Bug
Random structures/dungeons spawning within twilight forest dungeons.  This one completely broke this Ur-ghast tower.  We were able to dig around the locks, Ghast slaughtered the tower. etc.

https://clips.twitch.tv/DrabSmoothWhaleDuDudu

https://clips.twitch.tv/ResoluteZealousJayDoritosChip

## Expected Behavior
The tower should not be destructible/buildable inside.

## Possible Solution
Not sure if it's possible to push random structures further from twilight forest essential structures?

## Steps to Reproduce (for bugs)
Not Slaughter for the RNG Gods
Get Rekt by RNG Gods
Apologize to RNG Gods :P

## Context
Trying to complete the twilight forest quest, and trying to hit age 3 (Blood tears for fiery ingots) (the first hydra we killed also had 0 drops)

## Client Information

* Modpack Version: 3.0.5 (world was created in 3.0.3, Twilight created in 3.0.5)
* Java Version: 8
* Launcher Used: Twitch App

**Comment by artdude543** [comment] 2018-04-11 11:39
We changed/edited the Hydra drops in 3.0.6 so updating would fix that issue. In regards to the structure that would need some investigation to look into it and/or disabling them spawning in that dimension. But one part of the issue is already fixed 😄

**Comment by Phantum** [comment] 2018-04-12 02:12
ah ok, so all those issues should be fixed in 3.0.6 (with new explored chunks then? :)  )

**Comment by artdude543** [comment] 2018-06-06 10:02
Going to close this one. The main issue was fixed in regards to the drops. And the generation was fixed in the server files. And we can't really change how Vanilla handles generation w/o hacks.

**Closed by artdude543** 2018-06-06 10:02 UTC
Labels: Investigate Further, Priority: Medium, Type: Bug
