### ISSUE TITLE
more than one way to craft a crafting table not needed

### ISSUE THREAD

**Issue by captainbritian** [DarkPacks/SevTech-Ages#2325] opened 2018-05-10 15:47 UTC
when using the crafting station is you place 5 wood in the crafting table like this https://gyazo.com/1de34796999f74910535129d55264e62
it produces a crafting table  not a major bug but a small bug and if you place the wood like this 
https://gyazo.com/7f1b665f11ab4a4d5ef65992549c2d52
it produces slabs and it does craft these item's this was discovered on 3.0.6 and it persists in 3.0.7 
there is a few other hidden ways to make a crafting table in the crafting grid i do not know if you want to fix these issue's but i just want it known its not a game breaking bug so yeah

**Comment by artdude543** [comment] 2018-05-10 15:47
Duplicate of #705

**Closed by artdude543** 2018-05-10 15:47 UTC
