### ISSUE TITLE
Lost Grave and Horse Cart In Water

### ISSUE THREAD

**Issue by Drascalicus** [DarkPacks/SevTech-Ages#2739] opened 2018-06-03 21:34 UTC
So, I was trying to invade a shaggroth den when I died in the water. No big deal, so I return to my grave site, and I have no grave, there is nothing there. Same thing happened to my horse cart when it disconnected underwater. 

If you want to reproduce this, die in/underwater

**Comment by artdude543** [comment] 2018-06-03 22:47
Duplicate of #2429

**Closed by artdude543** 2018-06-03 22:47 UTC
Labels: triage
