### ISSUE TITLE
Crash Launcher

### ISSUE THREAD

**Issue by Alakatria** [DarkPacks/SevTech-Ages#3277] opened 2018-08-16 17:11 UTC
## Bug Report

My game is crashing everytime I launch the game, the launcher open minecraft then when i start loading the modpack the game is crashing.
Thanks for the help and for the modpack I love it ( Even more when it don't crash)

## Expected Behaviour

I have been playing the modpack before and everything was fine, the only factor that has change since the last launch was a windows update and minecraft realease the 1.13 

## Possible Solution

I updated java to latest version and resinstalle the modpack but no improvement 

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:
---- Minecraft Crash Report ----
[crash-2018-08-16_18.56.12-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2294561/crash-2018-08-16_18.56.12-client.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 181
* Launcher Used: twitch
* Memory Allocated: 5 GB
* Server/LAN/Single Player:
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: no modification to the original modpack

**Comment by artdude543** [comment] 2018-08-16 17:19
Duplicate of #3271

**Closed by artdude543** 2018-08-16 17:19 UTC
Labels: triage
