### ISSUE TITLE
Auto Cauldron requires unfamiliar Item

### ISSUE THREAD

**Issue by voltz20** [DarkPacks/SevTech-Ages#4139] opened 2020-06-06 20:43 UTC
## Bug Report
Auto Cauldron requires unfamiliar Item

## Expected Behaviour
All resources for modular machines are accessible in age creative

**Comment by sam-kirby** [comment] 2020-06-07 05:51
Duplicate of #3851

**Closed by sam-kirby** 2020-06-07 05:51 UTC
Labels: Duplicate
