### ISSUE TITLE
Stage Two Recipe for Wooden Axle Doesn't Give an Output Product

### ISSUE THREAD

**Issue by WolfBungalow** [DarkPacks/SevTech-Ages#3991] opened 2019-11-12 03:44 UTC
## Bug Report
The stage two recipe for a Wooden Axle doesn't give the an output product. JEI shows the recipe and will move the required 2x Plank Moldings and 1x Hemp Rope into a crafting table but this results in no Wooden Axle being shown as output.

## Expected Behaviour
The recipe should result in a Wooden Axle.

## Steps to Reproduce (for bugs)
Screen Recording: https://youtu.be/UxWecNNbjac

## Logs
* Crash Log: N/A

## Client Information
* Modpack Version: SevTech:Ages - 3.1.2 Hotfix 1 - (Release)
* Java Version: 1.8.0.51 (64 Bit)
* Launcher Used: Twitch Native Launcher / Ages (forge-14.23.5.2838)
* Memory Allocated: 8192 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: The Twitch launcher default version on 2019-08-04.
* Additional Content Installed: N/A

**Comment by sam-kirby** [comment] 2019-11-12 08:52
Duplicate of #3863 

This is a JEI display issue, arrange the components in a vertical line like below:

|     |     |     |
| --- | --- | --- |
|     |  M  |     |
|     |  R  |     |
|     |  M  |     |

where M is moulding and R is rope.

**Closed by sam-kirby** 2019-11-12 08:52 UTC
Labels: triage
