### ISSUE TITLE
JourneyMap integration for samples does not work for ContentTweaker samples

### ISSUE THREAD

**Issue by Iorce** [DarkPacks/SevTech-Ages#2874] opened 2018-06-13 17:07 UTC
## Bug Report

Shift-right clicking Geolysis samples adds them as a JourneyMap waypoint. Apart from the fact that it returns a Rock (probably a staging issue), doing it on ContentTweaker added samples (see: Osmium sample) does not work.

## Expected Behaviour

Should properly add a waypoint as for any other sample.

## Steps to Reproduce (for bugs)

1. Get to Stage 5
2. Shift-rightclick any sample
3. Shift-rightclick an Osmium sample

## Client Information

* Modpack Version: 3.0.7 (3.0.8 pending)
* Java Version: 1.8.0_161 64 bit
* Launcher Used: Twitch App
* Memory Allocated: 6400MB
* Server/LAN/Single Player: Server (SSP pending)
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: 3.0.6

* Additional Content Installed: no

## Server Information
* Java Version: unknown
* Operating System: unknown
* Hoster/Hosting Solution: unknown
* Sponge (Non-Vanilla Forge) Server: no

**Comment by artdude543** [comment] 2018-06-13 18:29
Duplicate of #2477

**Closed by artdude543** 2018-06-13 18:29 UTC
Labels: triage
