### ISSUE TITLE
Auto Cauldron (Modular Machines) isn't buildable as it requires Tiny Item Output 

### ISSUE THREAD

**Issue by xepps** [DarkPacks/SevTech-Ages#4033] opened 2020-01-15 22:42 UTC
## Bug Report
Go to Age 4,
Try to build the Auto Cauldron
See that the Tiny Item Output is registered as Unfamiliar Item
Optional:
Try to build Auto Cauldron Substituting Small Item Output
Structure not registered

## Expected Behaviour
Either Tiny Item Output available to craft in age 5, or
Other Item Outputs are available to build the multiblock with

## Possible Solution
Easiest fix is move `<modularmachinery:blockoutputbus:0>` to enabled in stage 4.
Happy to submit this on a PR. 
Unsure how to register alternate Item Outputs for the multiblock

## Steps to Reproduce (for bugs)
See above

## Logs
N/A

## Client Information
* Modpack Version: Version 3.1.2 Hotfix 1

**Comment by sam-kirby** [comment] 2020-01-15 23:47
Duplicate of #3851

**Closed by sam-kirby** 2020-01-15 23:47 UTC
Labels: triage
