### ISSUE TITLE
Bronze/Copper Pickaxe Recipe Bug

### ISSUE THREAD

**Issue by RobertLSnead** [DarkPacks/SevTech-Ages#3026] opened 2018-07-01 16:07 UTC
## Bug Report
Bronze pickaxe can be crafted with copper plates.  Unable to craft copper pickaxe.

## Expected Behaviour
To be able to craft pickaxe with it's corresponding plates.

## Possible Solution
Fix the recipe!

## Steps to Reproduce (for bugs)
Craft a copper pickaxe with copper plates, you will get a bronze pickaxe.
Unable to craft bronze pickaxe with bronze plates, recipe does not exist other than copper plates.

## Logs
N/A

## Client Information
SevTech: Ages - 3.0.8
Jun 8, 2018

## World Information
N/A

## Server Information
N/A

**Comment by RobertLSnead** [comment] 2018-07-01 16:12
This appears to be with all bronze/copper tools.
Was this intended?

**Comment by MelficeSilesius** [comment] 2018-07-01 16:56
Duplicate of #2802 

Issue is know, and presumably being worked on. Or not. Who knows?

**Closed** 2018-07-01 21:42 UTC
Labels: triage
