### ISSUE TITLE
Spartan Shield that are casted doesn't work

### ISSUE THREAD

**Issue by Pthread-Create** [DarkPacks/SevTech-Ages#3723] opened 2019-04-15 16:20 UTC
On Beta 3.1.1

Spartan Shield that are casted doesn't work with tinker construct

## Steps to Reproduce (for bugs)
Make a Crude Wood Shield from spartan
Cast another shield with wooden shield in the cast
the wooden shield stay in the cast you cannot and the liquid is bugged.

**Comment by sk2048** [comment] 2019-04-17 20:51
Duplicate of #3650

**Closed by sk2048** 2019-04-17 20:51 UTC
Labels: triage
