### ISSUE TITLE
Crashes when i open storage box or clicking E

### ISSUE THREAD

**Issue by valhalladidde** [DarkPacks/SevTech-Ages#3188] opened 2018-07-27 18:36 UTC
## Steps to Reproduce (for bugs)

1.try to open a storagebox or just press E
2.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/HVw1ATEk

## Client Information

* Modpack Version:3.0.8
* Java Version:
* Launcher Used:Twitch
* Memory Allocated:16G
* Server/LAN/Single Player: singel player
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:
[crash-2018-07-27_20.28.10-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2236830/crash-2018-07-27_20.28.10-client.txt)

**Comment by artdude543** [comment] 2018-07-27 23:15
Duplicate of #3118

**Closed by artdude543** 2018-07-27 23:15 UTC
Labels: triage
