### ISSUE TITLE
Pickle Tweaks lets me create a bronze pickaxe from copper before I have made bronze

### ISSUE THREAD

**Issue by bombcar** [DarkPacks/SevTech-Ages#2862] opened 2018-06-12 13:51 UTC
## Bug Report
I can craft a bronze pickaxe from copper plate, but I cannot craft a copper one. I've not even found tin yet.

## Expected Behaviour
I should be able to make the copper pickaxe, but not the bronze one.

## Possible Solution
Perhaps the names are reversed?

## Steps to Reproduce (for bugs)
1. Advance to Age 1, and find and smelt copper
2. Bronze pickaxe can be made from copper

## Client Information
* Modpack Version: 3.0.8
* Launcher Used: Twitch
* Memory Allocated: 4G
* Server/LAN/Single Player: Server

**Comment by artdude543** [comment] 2018-06-12 14:03
Duplicate of #2802

**Closed by artdude543** 2018-06-12 14:03 UTC
Labels: triage
