### ISSUE TITLE
Backpack on baubles disapear after diying by the sacrificial dagger whit keepinventory true

### ISSUE THREAD

**Issue by takashi1kun** [DarkPacks/SevTech-Ages#3265] opened 2018-08-14 13:54 UTC
Basically that
I tried to reproduce and happens always
the backpack from improved backpacks while stored on the baubles inventory slot, after diying by the use of the sacrificial dagger of blood magic and whit keepInventory true, disapears, whit other type of deaths do not diseapear and whitout keepinventory true it is not in the grave but remains equiped.
Steps to reproduce:
1 Equip a backpack from improved backpacks on the baublbes inventory slot
2 change the gamepropety of keepInventory to true
3 kill yourself whit the sacrificial dagger of blood magic
4 the backpack is not in the baubles inventory anymore, neither anywhere.

Sorry for my bad english, i reproduced this behavior like 10 times in a row in a controled enviorment and is consistent, and the backpack simply diseapears, is not droped or placed or anything, and only happens whit that specific type of death, while in the baubles inventory and whit that gameRule. 

Whitout the gamerule another strange behavior happens whit that type of death, it simply remains equiped after death and it should be on the tomb

UPDATE:
It is not backpack specific issue, it also happens whit other things on the baubles inventory

UPDATE2:
I tried disabling the tomb mod, and it remains the same, diying by dagger whit the gamerule baublbes inventory disapear, diying whitout the gamerule, baubles inventory does not drop off as it should, but remains in the inventory as it should happen whit the gamerule, but for some reason, whitout it

Is like if the keepInventory is disabled, and you die whit the dagger it works for baubles as if keepInventory was enabled, and if the keepInventory is enabled and die whit the dagger, it just vanishes in to oblivion the baubles inventory.

**Comment by artdude543** [comment] 2018-08-14 17:16
Duplicate of #2429 (It's all down the grave mod in use which is changed in 3.1.0)

**Closed by artdude543** 2018-08-14 17:16 UTC
Labels: triage

**Comment by takashi1kun** [comment] 2018-08-15 03:06
Is not the grave mod, I removed it and presents the same behavior

**Comment by takashi1kun** [comment] 2018-08-15 03:10
And is not a duplicate of that, this issue and that issue don't have nearly anything in common

**Comment by artdude543** [comment] 2018-08-15 19:02
Then it would need reporting to both/either BM/Baubles.
