### ISSUE TITLE
Hydra in Twilight Killed me, destroyed my grave and now I cant get extra hearts back.

### ISSUE THREAD

**Issue by monkeydew123** [DarkPacks/SevTech-Ages#2759] opened 2018-06-05 07:27 UTC
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Tahakk** [comment] 2018-06-05 07:40
Fill the template, it is not there just to be fancy

**Comment by artdude543** [comment] 2018-06-05 09:56
Duplicate of #2429

**Closed by artdude543** 2018-06-05 09:56 UTC
Labels: triage

**Comment by LordHellscream** [comment] 2018-06-11 18:33
you died and you lose nutrition from death, when your nutrition goes under 90% you lose HP bonus,
