### ISSUE TITLE
[3.1.2.h1] Knightly metal Resistance 3 buff being renewed by Nutrition 

### ISSUE THREAD

**Issue by TrueLecter** [DarkPacks/SevTech-Ages#3900] opened 2019-08-23 16:26 UTC
## Bug Report
When you have Resistance I buff from nutrition and then get Resistance III buff by hitting enemy using weapon from knightly metal, it will be renewed every time with other nutritions buffs. Not sure if this is visual only bug, but seems like not visual. 

## Expected Behaviour
Separate resistance buffs or Resistance I being applied after Resistance III ends.

## Possible Solution
IIRC in 3.0.8 there was a bit different behaviour, when Resistance III was overridden by Nutritions. Both behaviours 

## Steps to Reproduce (for bugs)
1. Fill nutritions enough to receive Restatence I buff 
2. Get Resistance III buff from Knightly weapon
3. Enjoy permanent (almost) 60% dmg reduction buff.
 
## Client Information

* Modpack Version: 3.1.2
* Java Version: 1.8 211
* Launcher Used: MultiMC 5 (0.6.7)
* Memory Allocated: 16384
* Server/LAN/Single Player: LAN
* Optifine Installed: true
* Shaders Enabled: false

## World Information

* Modpack Version world created in: 3.0.8, upgraded to 3.1.2

* Additional Content Installed: Optifine 1.12 HD Ultra E3, Just Enough Calculation 3.2.0

**Comment by sk2048** [comment] 2019-08-23 18:03
Effectively a duplicate of #3874, same cause. Thanks for the report anyway.

**Closed by sk2048** 2019-08-23 18:03 UTC
Labels: Duplicate
