### ISSUE TITLE
Can't make a Bronze Plated Shield

### ISSUE THREAD

**Issue by Melexie** [DarkPacks/SevTech-Ages#3655] opened 2019-03-24 19:53 UTC
## Bug Report
Whenever I try to create a Bronze Plated Shield in my smeltery something goes wrong. I can only get the smeltery to pour out the molten bronze for about a millisecond per try and sometimes nothing happens. The Caster Table I'm pouring the bronze into, which also has a Crude Wooden Shield in it, can tell me that bronze does pour into it, just very small amounts per time. If I can reach the maximum amount which should transform the Crude Wooden Shield into a Bronze Plated Shield the transformation will start, but even after it reaches 100% there's still only a Crude Wooden Shield in the Caster Table (though the textures of the Crude Wooden Shield and the Bronze Plated Shield have merged in the Cater Table). If I check the amount of Bronze in the smeltery, nothing has disappeared, which it should have.
If I disconnect and join the server again, the Crude Wooden Shield is still in the Caster Table, but the bronze that was in the Casting Table is gone and the smeltery has exactly the same amount of bronze that it had before I disconnected, aka. the same amount that's been in there from the start.

There's no trouble making anything with casts and bronze, like ingots. Blocks of bronze are also possible to make with no trouble.

![Screen Shot 2019-03-24 at 17 39 57](https://user-images.githubusercontent.com/9579856/54884907-bc134e00-4e76-11e9-8b16-586a80de930e.png)
![Screen Shot 2019-03-24 at 17 39 52](https://user-images.githubusercontent.com/9579856/54884908-bc134e00-4e76-11e9-9e46-a902e46b3bc8.png)

## Expected Behaviour
When bronze is poured into a Casting Table with a Crude Wooden Shield in it should after a short while turn into a Bronze Plated Shield and one click on the faucet should be enough to pour all the way to the top (unless the bronze in the smeltery runs out).

## Steps to Reproduce (for bugs)

1. Put a Crude Wooden Shield in a Casting Table.
2. Click on the faucet on the smeltery with bronze in the bottom.

## Logs

* Client/Server Log: https://paste.atlauncher.com/view/735e73ab
* Crash Log: 

## Client Information

* Modpack Version: Sevtech: Ages 3.1.1
* Java Version: Java 8 Update 201
* Launcher Used: ATLauncher
* Memory Allocated: 4 gb
* Server/LAN/Single Player: Server and Single Player
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in: Server 3.0.6 and Single Player 3.1.1

* Additional Content Installed:

## Server Information
* Java Version: 1.8.0_201-b09
* Operating System: Windows 10

**Comment by Ineffizienz** [comment] 2019-04-01 09:37
Hi,
I can confirm that issue.
You try to fill the Caster Table with bronze, so pour out the required amount of bronze. While try to get this bronze you sometimes noticed that nothing happens. In that moment, if you look into the smeltery controller, the whole bronze is gone. Leave the controller and enter it again, the bronze is back so you can start trying to pour out the bronze.
Still if the Caster Table contains the required amount the transformation does not happen as described above. 

Modpack Version: 3.1.1
Modpack Version world created in: Single Player 3.0.8

**Comment by justinrusso** [comment] 2019-04-05 18:09
Duplicate of #3650

**Closed by justinrusso** 2019-04-05 18:09 UTC
Labels: Duplicate
