### ISSUE TITLE
Sevtech Wont Load Game

### ISSUE THREAD

**Issue by SlimeVampire** [DarkPacks/SevTech-Ages#2893] opened 2018-06-15 22:24 UTC
## Bug Report
 My game will launch on a fresh install but if i close it and i try to load up pack again, it wont load up
 ee what the issue is and see if there is a fix

## Expected Behaviour
 Game wont load, and this happens to every instance that i make, it can run once but not multiple times

## Possible Solution
Have no idea, probably something to do in mod loading process

## Steps to Reproduce (for bugs)

1. Launch game once
2. Play for a while
3. Save game and quit
4. close out game
5. restart game

## Logs
* Client/Server Log: https://gist.github.com/SlimeVampire/fb175e44e9888451516043a215eafe2e
* Crash Log: https://gist.github.com/SlimeVampire/916bf14e34f4c5962f5e80cbdfa5f435 

* Modpack Version: 3.0.8
* Java Version: 1.8
* Launcher Used: MultiMC (Export From Twitch)
* Memory Allocated: 10112 mb
* Server/LAN/Single Player: All
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
 
* Modpack Version world created in: 3.0.8

* Additional Content Installed: Optifine

* Sponge (Non-Vanilla Forge) Server: Normal World Type

**Comment by Stifling-Bossness** [comment] 2018-06-15 22:29
Did you change key bindings? Try keeping them default and try again.

**Comment by SlimeVampire** [comment] 2018-06-15 23:08
Ok that worked but idk how... tht makes no sence lol

**Comment by Stifling-Bossness** [comment] 2018-06-15 23:42
Yeah, it's definitely a _very_ odd bug, but it seems to have been reported before. #1180

**Comment by justinrusso** [comment] 2018-06-16 00:36
Duplicate of #1180

**Closed by justinrusso** 2018-06-16 00:36 UTC
Labels: triage
