### ISSUE TITLE
Creative Opening Inventory Crash

### ISSUE THREAD

**Issue by nerdyjoe314** [DarkPacks/SevTech-Ages#3179] opened 2018-07-26 13:58 UTC
## Bug Report

I started a new world in creative, went to open my inventory and the game crashed.

## Expected Behaviour

I expected to be able to see the normal creative inventory.

## Possible Solution

It might have to do with JEI trying to render something that isn't meant to be rendered.

## Steps to Reproduce (for bugs)

1. Click Singleplayer
2. Create New world
3. Change game mode to creative
4. Create New world
5. Press the 'e' key

## Logs

* Client/Server Log: https://gist.github.com/nerdyjoe314/957c65b7d2b279349cdc2dc00edc1991
* Crash Log: https://pastebin.com/bWm3tdzU

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8.181
* Launcher Used: Twitch
* Memory Allocated: 8084 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Sevtech ages 3.0.8

* Additional Content Installed:

**Comment by artdude543** [comment] 2018-07-26 15:04
Duplicate of #3118

**Closed by artdude543** 2018-07-26 15:04 UTC
Labels: triage
