### ISSUE TITLE
Game and server crashing due to Streams/Farseek mod

### ISSUE THREAD

**Issue by Lairdjoker** [DarkPacks/SevTech-Ages#4005] opened 2019-12-15 17:33 UTC
## Bug Report
When exploring the world we have random crashed that seem to be assosiated with Streams generation. The server first lags then completely hangs and crashes. I have looked at the mod developers page and currently there does not seem to be a fix so I am hoping that with the amount of people that play this mod that there has been a fix.

## Steps to Reproduce (for bugs)
To repoduce this mod you need to explore in the warm/hot heat zones where the streams generate.

## Logs
* Client/Server Log: 
[crash-2019-12-15_17.01.53-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/3965206/crash-2019-12-15_17.01.53-server.txt)

## Client Information

* Modpack Version: 3.1.2 Hotfix 1
* Java Version: Java 8 v231
* Launcher Used: Curse
* Memory Allocated: 12GB Client, 8GB Server
* Server/LAN/Single Player: Server
* Optifine Installed: Yes (but others have crashed without it)
* Shaders Enabled: Yes (but others have crashed without it)

## World Information

* Modpack Version world created in: 3.1.2 Hotfix 1

* Additional Content Installed: Updated Farseek to Farseek-1.12-2.4 (did not help)

## Server Information
* Java Version: Not sure
* Operating System: Not sure
* Hoster/Hosting Solution: ZAP Hosting
* Sponge (Non-Vanilla Forge) Server: Not sure

**Comment by sam-kirby** [comment] 2019-12-15 18:05
Duplicate of #3902

**Closed by sam-kirby** 2019-12-15 18:05 UTC
Labels: triage
