### ISSUE TITLE
All wood molding turning into mulberry variant 

### ISSUE THREAD

**Issue by Furionstrom** [DarkPacks/SevTech-Ages#3062] opened 2018-07-07 12:12 UTC
## Bug Report
When using the BWM saw all molding that is created turns into mulberry wood which cannot be used in all recopies for instance the wood slats needed for the composting bin.

## Expected Behavior
you get the molding for the wood variant used 

## Steps to Reproduce (for bugs)
1. Make wood molding with the BWM saw

## Client Information
* Modpack Version: 3.0.8
* Java Version:
* Launcher Used: MultiMC
* Memory Allocated: 6gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed:  Scematica

## Server Information NOt sure about this info
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-07-07 22:30
Duplicate of #2916

**Closed by artdude543** 2018-07-07 22:30 UTC
Labels: triage
