### ISSUE TITLE
crash while loading world

### ISSUE THREAD

**Issue by MikeHekman** [DarkPacks/SevTech-Ages#4291] opened 2020-09-24 18:25 UTC
## Bug Description

 I went flying with the volarkite and suddenly my game crashed. I tried to restart the modpack and everytime i try to load the world it crashes as soon as i load in to the world.

### Did this behavior use to work in the previous version?

 The current version

## Steps to Reproduce (for bugs)

1. start the modpack
2. load the world
3. game crashes every time

## Logs

* Client/Server Log:  https://pastebin.ubuntu.com/p/BVNF73fBdW/ 
* Crash Log:  https://pastebin.ubuntu.com/p/GbvWq6HnFF/ 

## Client Information
* Modpack Version: 3.2.0, minecraft 1.12.2
* Java Version: 1.8.0_51
* Launcher Used: twitch
* Memory Allocated: 7054MB
* Server/LAN/Single Player: Single Player
* Optifine Installed:  False for the crash log, was installed before and did also crash
* Shaders Enabled: False

## World Information
* Modpack Version world created in: 3.2.0
* Additional Content Installed: none

**Comment by sam-kirby** [comment] 2020-09-24 18:26
Duplicate of #4256

**Closed as completed by sam-kirby** 2020-09-24 18:26 UTC
Labels: Duplicate
