### ISSUE TITLE
Trying to craft a piston in Refined Storage Crafting Grid crashes

### ISSUE THREAD

**Issue by stinyc** [DarkPacks/SevTech-Ages#4222] opened 2020-08-21 22:32 UTC
## Bug Description

Trying to use JEI to craft a piston in a Refined Storage Crafting Grid will crash the world, sending you back to the title screen. Placing the items in manually works fine. Error: Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes.

### Did this behavior use to work in the previous version?

Not sure, never played previous versions.

## Steps to Reproduce (for bugs)

1. Make Refined Storage controller, disk drive, and crafting grid, and put the items for a piston into the system.
2. Click the recipe for a piston in JEI.
3. Click the plus sign to move the items into the crafting grid.

## Logs

* Client/Server Log: https://gist.github.com/poopydangle/7f4fc070fa4543dc0251db3225f0a05d
* Crash Log:

## Client Information
* Modpack Version: 3.1.2 Hotfix 1
* Java Version: 1.8.0_261-b12
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.1.2 Hotfix 1
* Additional Content Installed: Just Optifine 1.12.2_HD_U_F5

**Comment by sam-kirby** [comment] 2020-08-21 23:14
Duplicate of #2498

**Closed as completed by sam-kirby** 2020-08-21 23:14 UTC
