### ISSUE TITLE
[3.0.7][Crash]ImmersiveTech Alternator/Steam Turbine Crash

### ISSUE THREAD

**Issue by TheCheif** [DarkPacks/SevTech-Ages#2574] opened 2018-05-22 07:27 UTC
So i built an Steam Turbine halfway into a cave, the front is free, but the part with the iron core is in a cave. The Machine glitched out, as i hammered it with the engineers hammer. It's hard to describe what happens but it basically showed or built the Alternator itself (the part of the machine, where the plugs are, don't remember the exact names). But instead of 3 plugs on one side of the Machine it had like 12 on each side. I would take a Screenshot but my Game immediatly crashes when i log in. I play on a Server and the Server doesn't crash only my Client.

Crash Report: https://pastebin.com/9y5D299D

**Comment by TheCheif** [comment] 2018-05-22 07:31
As i was looking through the Crash Report, i saw that waila had a problem with something so i tried to look straight down right as i logged in and i was able to take a screenshot that way. As you can see, i even destroyed the first machine, but the alternator plugs are still there.

![2018-05-22_09 29 40](https://user-images.githubusercontent.com/1868365/40348116-f13d9a88-5da2-11e8-96b9-c31056c42611.png)

**Comment by FluffyDiscord** [comment] 2018-05-22 10:39
just use MCEdit adn remove that machine from the world

**Comment by artdude543** [comment] 2018-05-22 16:36
Going to tag this under another issue for now so we have one place for it as it's the same crash and mod involved 
Duplicate of #2442

**Closed by artdude543** 2018-05-22 16:36 UTC
Labels: triage
