### ISSUE TITLE
Metal press duplication

### ISSUE THREAD

**Issue by C14X** [DarkPacks/SevTech-Ages#4170] opened 2020-06-24 19:49 UTC
## Bug Description

 Sometimes when I use the 2x2 or 3x3 packing presses with the metal press, upon throwing resources on it, it will create an output without consuming any inputs, allowing resource multiplication. I've seen this with clay and platinum blocks.

### Did this behavior use to work in the previous version?

 Yes, the bug did not occur in 3.1.2.

## Steps to Reproduce (for bugs)

1. Set up metal press, and put the 2x2 or 3x3 presses in it.
2. Throw resources that would result in a recipe on it.
3. Figure out how many outputs you should have, and see if you have extra. It doesn't always happen, but it has happened several times.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
* Modpack Version: 3.1.3
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player: Single player.
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in: 3.1.2
* Additional Content Installed:

**Comment by sam-kirby** [comment] 2020-06-24 19:55
Can you please attach your log?

**Comment by Conno2429** [comment] 2020-06-25 06:08
While I play, the metal press won't consume items as long as you are next to the metal press picking up the items. Ex: Throw 10 blocks of iron with 3x3 mold to create iron block, iron block gets created but you receive all 10 iron back. It works with all molds. As long as you are standing next to the metal press and picking up items, it will work.

**Comment by sam-kirby** [comment] 2020-06-25 06:11
Which version @Conno2429?

**Comment by Conno2429** [comment] 2020-06-25 06:35
3.1.2 hotfix 1

**Comment by sam-kirby** [comment] 2020-06-25 12:46
That's expected, see #3732 

What would be unusual is this still occurring in 3.1.3 - changes I made in SevPatches should fix this, and I am unable to reproduce the behaviour described by @C14X in 3.1.3.

**Comment by joshpro8423** [comment] 2020-06-29 00:02
I've figured out a consistent way to reproduce the bug. If you throw more than 2x the amount of a resource onto the press and let it sit, you will always get 1 more extra

You can also throw more than 2x the amount onto the press then immediately turn on the cyclic magnet to pick it up and you get all of it back but it still processes the craft

Been very consistent from my testing

**Comment by sam-kirby** [comment] 2020-06-29 04:12
What version are you playing @joshpro8423?

**Comment by joshpro8423** [comment] 2020-06-29 05:14
> What version are you playing @joshpro8423?
> 
> From your other issues, it seems you’re playing 3.1.2. We know this issue happened in 3.1.2, I can reproduce it in 3.1.2 and know why it occurs in 3.1.2. It should be fixed in 3.1.3, where I cannot reproduce it.
> 
> **Please only add to this discussion if you are playing 3.1.3 and can reproduce this issue, preferably with steps.**

If there's a version 3.1.3 then for some reason i cant see the latest update; im running it on the twitch launcher and it tells me the latest version is 3.1.2 hotfix 1

**Comment by joshpro8423** [comment] 2020-06-29 05:23
Ive updated the twitch app and it now detects the new update, ignore the previous reply

**Comment by sam-kirby** [comment] 2020-09-19 00:27
As nobody has demonstrated this issue is present in 3.1.3+, I am closing this.

**Closed by sam-kirby** 2020-09-19 00:27 UTC
Labels: Status: Cannot Reproduce, Status: Needs more Information
