### ISSUE TITLE
Water Wheel Duplication Glitch (BetterWithMods)

### ISSUE THREAD

**Issue by CuriousDark** [DarkPacks/SevTech-Ages#3218] opened 2018-08-03 20:05 UTC
## Bug Report
When breaking an axle with a water wheel on it water wheel (from 'better with mods') with a stone axe, (only axe I tested) two water wheels drop along with the original axle.

## Expected Behaviour
When breaking the water wheel, it should drop one wheel, not two.

## Steps to Reproduce (for bugs)
1. Place axle above water.
2. Place water wheel on axle.
3. Break axle with stone axe.
4. Two water wheels drop.

## Logs
Launcher Logs showed nothing of interest (trust me)

## Client Information
* Allocated 16G of Ram.
* Modpack Version: 3.0.8
* Java Version: Version 8 Update 181
* Launcher Used: Twitch
* Memory Allocated: 16G
* Server/LAN/Single Player: SP
* Optifine Installed: yes
* Shaders Enabled: yes

## World Information
* Modpack Version world created in: 3.0.8

**Comment by monodemono** [comment] 2018-08-03 21:13
Duplicate of #2971

Please use the search feature before reporting issues.

**Closed by monodemono** 2018-08-03 21:13 UTC
Labels: triage
