### ISSUE TITLE
[3.0.7] Astikoor (Horse) cart is getting lost (single player)

### ISSUE THREAD

**Issue by BiZZKeryear** [DarkPacks/SevTech-Ages#2556] opened 2018-05-21 12:19 UTC
Might or might not  be related to https://github.com/DarkPacks/SevTech-Ages/issues/1812
## Issue / Bug
When traveling around with a cart I have noticed some strange behavior.
Aside that the cart is getting stuck for no reasons, and it also moves while the horse is standing still (rotates).
1. If I get to my destination with my cart I sometimes find that the cart vanishes after a while ... only to find it down the road.
   1. Sometimes I see it from afar only to have it vanish and reappear at the horse.
   2. Sometimes it has getting stuck but not registered (or so it seems often I can't tell)
   3. Sometimes even if I find the cart it isn't there.
Because if I open the cart and put things into it it seems to work only that that is undone later (items reappear in my inventory)
I also think moving the cart will be counterproductive at that point. So I reloaded. (and found the cart somewhere else. Though, I don't remember where it was)
2. After such incidents and reloading the game (see "fix") the cart is it's true location where ever it is (often includes searching the cart) but the horse then acts (after reattaching the cart to the horse) as if the horse is not attached to the cart. (normal behavior: horse + cart = horse is staying in place; unlike the horse alone which wanders of)
Which is annoying since you will find the cart as well down in a ravine if not careful**
edit: Cart is every time detached from the horse after loading. And kinda it isn't, since the horse behaves like it isn't attached to the cart if it then is.

## Expected Behavior
none of the above

## Possible Solution
* Restarting the session helps
No need for restarting minecraft, though, just going to main menu and loading the game again. Then everything is in sinc again, well most of it. (see 2)
* *= to fix 2, attaching, the cart several times helps ... sometimes it needs restarting the game after that procedure.
* Sometimes (after this "fix") I then find the cart:
   * where it should be (behind the horse).
But often if not always not attached to the horse, though
or in the wired half attached state mentioned above
   * where it got stuck (e.g. at a corner, on a tree next to road)
   * where it shouldn't be (e.g. under a bridge or up a hill next to the road)
fortunately not under one of the bridges that are going over a ravine or a river ... or the new one I'm building over the ocean (hope that will not be, never used that bridge since I am still building on it ... got tricked by antique atlas now almost half of it is done ... I might as well finish it)
 
## Steps to Reproduce (for bugs)
Chance seem to rise after letting the game running for some hours, so it does to travel over small roads (made grass roads [shovel right click], three blocks high [through trees and if in tunnel], two blocks wide, with half a block elevation [means half slabs when it is going up / down])

## Client Information
* Modpack Version: 3.0.7
* Java Version: 8 Update 172, 64-bit
* Launcher Used: MultiMC
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Jandakast** [comment] 2018-05-21 22:19
Duplicate of #1812 

This is likely a desync issue that we can not do anything about.

**Closed by Jandakast** 2018-05-21 22:19 UTC
Labels: triage
