### ISSUE TITLE
SevTech stopped launching starting today

### ISSUE THREAD

**Issue by G9third** [DarkPacks/SevTech-Ages#3280] opened 2018-08-16 17:45 UTC
Hello! I play with a group of 8 friends on a SevTech 3.0.8 private server. Starting this morning, all of our games (including mine) crash at the exact same time [The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game]. Last night the game was working fine, but just today suddenly all of our games have stopped being able to launch without crashing. The similarities between all of our PC's are: 
We all have Nvidia GPU's
All running windows 10
All have latest nvidia drivers
All using latest java x64 and have at least 5Gb allocated to the modpack
That's about it.
I have tried reinstalling many times but it's never worked. Same with everyone else.

Here is the link for PasteBin: [here](https://pastebin.com/BBnK06sH)

**Comment by artdude543** [comment] 2018-08-16 17:47
Duplicate of #3271

**Closed by artdude543** 2018-08-16 17:47 UTC
Labels: triage
