### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by alexHunter854** [DarkPacks/SevTech-Ages#4269] opened 2020-09-20 01:57 UTC
## Bug Description

 it just randomly crashed when i was flying around

### Did this behavior use to work in the previous version?

Version: don't know...

## Steps to Reproduce (for bugs)

 it just happend randomly, i can't figure out what i was doing that made it crash 

## Logs

* Client/Server Log: [log](https://pastebin.com/Bm4me2j1)
* Crash Log:

## Client Information
* Modpack Version: 3.2.0-alpha
* Java Version: 1.8.0_51
* Launcher Used: oficcal minecraft luancher
* Memory Allocated: 7144mb
* Server/LAN/Single Player:single player
* Optifine Installed: no
* Shaders Enabled: no

## World Information
* Modpack Version world created in: 3.2.0-alpha
* Additional Content Installed: none

**Comment by justhayleyk** [comment] 2020-09-20 03:59
I experience the same issue earlier today - not my game will not load at all.

**Comment by justhayleyk** [comment] 2020-09-20 04:00
I experienced the same issue earlier today - now my game will not load at all.

**Comment by sam-kirby** [comment] 2020-09-20 05:40
Duplicate of #4256 

Restore a backup.

**Closed as completed by sam-kirby** 2020-09-20 05:40 UTC
