### ISSUE TITLE
JAFF is incompatible with Mohist

### ISSUE THREAD

**Issue by shaotz** [DarkPacks/SevTech-Ages#4497] opened 2021-01-30 03:50 UTC
## Bug Description

Server crashes when specific dimension is being loaded.(StackOverflow, suspecting JustAFewFish.)
Seemingly, JAFF would fall into a loop that is to
               [- Create(Populate?) Chunk
                - Spawn Fish 
                - ? Other functions
                - Check for Tanks and Fluids (isInTank, and func_70692_ba is " return !this.isInTank") 
                - Chunk is not loaded
                - Create(Populate?) Chunk ]
Btw, JAFF's spawning fish is disabled in it's config file (\config\JAFF.cfg), but all parameters in the CFG file seemed not working(they're still spawning!) except for Spawn Frequency ......

## Steps to Reproduce (for bugs)

1.Fresh start the server for new worlds.
2.Join the server and quit the server aside the river(btw check out if there's any fish created by JAFF)
3.Restart the server

## Logs

* Client/Server Log:Mohist: https://gist.github.com/shaotz/55561dced9dc78de2fc4d8d1a0dc5a74 / CatServer: https://gist.github.com/shaotz/5fdaddf71e8e9bc4b98c514c28b0a999
* Crash Log:Mohist: https://pastebin.com/4GhgniBf  / CatServer: https://pastebin.com/TaaUZumZ

## Client Information
* Modpack Version:3.2.1
* Java Version:8u281
* Launcher Used:HMCL
* Memory Allocated:10GB
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## World Information
* Modpack Version world created in:3.2.1
* Additional Content Installed:No

## Server Information
* Java Version:8u131
* Operating System:Windows Server 2008 R2
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:Yes. Tried Mohist and CatServer (not original Sponge)

**Comment by shaotz** [comment] 2021-01-30 04:02
Server could be started if JAFF is removed, but all the recipes that the developers had customized with CraftTweaker would be replaced with the original Minecraft or Mods recipes.
  So is there a way to maintain the customized recipes and keep JAFF removed, for alternatives?
  Thanks!

**Comment by sam-kirby** [comment] 2021-01-30 06:34
We have had to make extensive modifications to Just A Few Fish to make it work in this pack - see here: https://github.com/DarkPacks/SevPatches#just-a-few-fish-augmentation-jaffa

In this pack, fish spawning is completely controlled by InControl. JAFF’s own config is ignored. If you remove the InControl spawning rules, spawning should stop.

The bug you reference, however, is not present when using a stock Forge server. It is introduced by Mohist, but they have thus far ignored it. See Mohist-Community/Mohist#379. It is not caused by our pack or modifications we make to the mod as it can be replicated with just Mohist + JAFF.

We do not investigate issues present only in modified packs due to a lack of time. I would ordinarily suggest you seek support from the developer of JAFF or Mohist, though I’m not sure that will get you very far in this instance as JAFF’s developer has gone silent, whilst Mohist have previously refused to acknowledge the issue. If, however, you do find a fix for this issue we will gladly include it in the pack if you submit it to us - including further patches to JAFF.

To workaround the issue, you could try removing the fish spawning rules. Or just use the stock Forge server.

**Comment by shaotz** [comment] 2021-01-30 07:12
> We have had to make extensive modifications to Just A Few Fish to make it work in this pack - see here: https://github.com/DarkPacks/SevPatches#just-a-few-fish-augmentation-jaffa
> 
> In this pack, fish spawning is completely controlled by InControl. JAFF’s own config is ignored. If you remove the InControl spawning rules, spawning should stop.
> 
> The bug you reference, however, is not present when using a stock Forge server. It is introduced by Mohist, but they have thus far ignored it. See [Mohist-Community/Mohist#379](https://github.com/Mohist-Community/Mohist/issues/379). It is not caused by our pack or modifications we make to the mod as it can be replicated with just Mohist + JAFF.
> 
> We do not investigate issues present only in modified packs due to a lack of time. I would ordinarily suggest you seek support from the developer of JAFF or Mohist, though I’m not sure that will get you very far in this instance as JAFF’s developer has gone silent, whilst Mohist have previously refused to acknowledge the issue. If, however, you do find a fix for this issue we will gladly include it in the pack if you submit it to us - including further patches to JAFF.
> 
> To workaround the issue, you could try removing the fish spawning rules. Or just use the stock Forge server.

Thank you for answering my questions!

**Closed as completed** 2021-01-30 07:12 UTC
Labels: Env: Sponge, Type: Crash, Env: Server, Category: Mod
