### ISSUE TITLE
Divination Sigal not showing blood altar capacity or contents

### ISSUE THREAD

**Issue by ImTheStigHonest** [DarkPacks/SevTech-Ages#2544] opened 2018-05-20 13:00 UTC
## Expected Behavior
when selecting the blood altar should see the altar information, tier, capacity contents.

only shows LP value

## Steps to Reproduce (for bugs)

1.click or shift click altar only show current LP network value no altar information
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by ByteTemplar** [comment] 2018-05-20 14:44
This is known bug and awaiting mod makers response...
https://github.com/DarkPacks/SevTech-Ages/issues/2216

**Comment by Jandakast** [comment] 2018-05-20 14:54
Duplicate of #2216

**Closed by Jandakast** 2018-05-20 14:54 UTC
Labels: Duplicate
