### ISSUE TITLE
CarryOn dupe

### ISSUE THREAD

**Issue by MCChiter** [DarkPacks/SevTech-Ages#1821] opened 2018-04-14 14:12 UTC
If you put breeding harness onto a cow and then shift-rclick it to pick up ass usual, you'll pick entity up AND cause the harness to fall off, resulting in a dupe (Cow keeps breeding harness) Not particularly useful in any way, just weird. From long enough distance you can pick the harness off without the dupe.

**Comment by LadyRyl** [comment] 2018-04-21 05:12
This happens with sheep as well.

**Comment by artdude543** [comment] 2018-05-28 22:59
This won't be fixed due to how complex the issue is and the mods involved. BWM won't add a check to see if the player is trying to use CarryOn nor so I see a valid point to do so. As this is an interaction issue. It may be fixed later down the line. But for now, it's not something major on our to-do list.

**Closed by artdude543** 2018-05-28 22:59 UTC
Labels: Category: Mod, Status: Known Limitation, Type: Bug
