### ISSUE TITLE
Chisel: Lapis Lazuli unable to be chiselled

### ISSUE THREAD

**Issue by TheKedart** [DarkPacks/SevTech-Ages#3955] opened 2019-09-29 22:16 UTC
## Bug Report
Lapis Lazuli Blocks are unable to be chiselled, despite chiselled versions being listed as available in JEI. The issue appears to be that the actual "Minecraft" version of the Lapis Lazuli block is not listed under the Chisellable blocks (so Chisel doesn't understand that it's related to the chiselled versions).

## Expected Behaviour
Expected to be able to chisel Minecraft Lapis Lazuli blocks into Chiselled versions.

## Client Information
* Modpack Version: 3.1.2 (Hotfix 1)

**Comment by sam-kirby** [comment] 2019-09-30 06:39
Duplicate of #3932 

Fixed for next version.

**Closed by sam-kirby** 2019-09-30 06:39 UTC
Labels: Duplicate
