### ISSUE TITLE
Bricks Slab Recipe Overlaps Bricks Stairs

### ISSUE THREAD

**Issue by dani154** [DarkPacks/SevTech-Ages#2635] opened 2018-05-26 06:37 UTC
## Bug Report
The bricks slab recipe is possible to craft when ther are other bricks in the left column and in the middle which overlaps the stairs recipe

## Expected Behaviour
Craft brick stairs with stair pattern
Craft brick slabs with slab pattern 

## Steps to Reproduce (for bugs)

1.Open Crafting Table
2.Place Bricks at the bottom row
3.Then place bricks in the left column up
4. And the last in the middle
5. There is a Stair pattern but it shows slabs
 
## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.71
* Launcher Used: Twitch Jar launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: SP
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment] 2018-05-26 10:42
Duplicate of #705

**Closed by artdude543** 2018-05-26 10:42 UTC
Labels: triage
