### ISSUE TITLE
Horse Status not appearing in WAILA 

### ISSUE THREAD

**Issue by fufu87** [DarkPacks/SevTech-Ages#2320] opened 2018-05-10 14:16 UTC
## Issue / Bug
Horse Speed and Strength not appearing in WAILA when looking at the horses 

![2018-05-10_17 18 09](https://user-images.githubusercontent.com/35885785/39873638-90e29bc2-547c-11e8-8b4a-fc4524e0ce76.png)

## Expected Behavior
As seen in the picture above, the jump strength and speed is not displayed for some reason

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Jar

* Memory Allocated: 6GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by MaxFirestorm** [comment] 2018-05-10 15:59
Also confirming

**Comment by SupremeMikki** [comment] 2018-05-11 20:56
Has anyone found a fix for this? I thought it was intended as part of the progression system until I seen it work fine on someone's video.

**Closed** 2018-06-05 10:14 UTC
Labels: Category: Mod, Status: Reported To Mod
