### ISSUE TITLE
Tinkers' Part Builder & Stencil Table showing multiple images in JEI, but only one works.

### ISSUE THREAD

**Issue by JackRuby1** [DarkPacks/SevTech-Ages#704] opened 2018-03-18 04:41 UTC
Both the part builder, and the stencil table have multiple types you can craft in JEI, only 1 of each of them (the plain oak version), shows the recipes, which it cycles through all of the  different types.
SevTech Sub Server version Beta 3

**Comment by justinrusso** [comment] 2018-03-18 13:49
Right, but does it still come up with a different one when you put a different wood in it?

The reasoning for that is because theres no need for 50 of the same thing showing in JEI. Its just extra clutter.

**Comment by JackRuby1** [comment] 2018-03-18 17:06
Ok, somehow it glitched out. It was showing all the varieties last night, but when I went on today it was only showing the one picture in JEI(still cycling through when you click on it for the recipe). Crafting with the different ones, show the recipes for the other ones.

**Comment by Darkosto** [comment] 2018-03-19 21:49
Okay, just to clarify: This is not a reproducible issue?

**Comment by justinrusso** [comment] 2018-03-24 07:17
Gonna close this as jack cant reproduce this either

**Comment by JackRuby1** [comment] 2018-04-05 04:07
@Darkosto and @justinrusso just reproduced this right now in. On thebryanboru's server. He also sees the same thing as well as me.
Part builder: https://gyazo.com/1e917babfeead549cfcab133823c0436
Stencil table: https://gyazo.com/7611b42de54f2168940bbfbd66987588
* Modpack Version: 3.0.4
* Java Version: Latest 8
* Launcher Used: Jar
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Soartex
* Optifine Installed?: No - but Bryan does.

**Comment by JackRuby1** [comment] 2018-04-05 04:52
I relogged and they mostly disappeared except for some kepler wood ones for stencil and a weedwood for part builder, none had recipes except for the one that's suppose to.
Stencil table: https://gyazo.com/aae2462a0e947cbe8a13f82d47c44075
Part builder: https://gyazo.com/17a61f033a1f8c77179aa635e04451be

**Comment by justinrusso** [comment] 2018-04-05 17:07
Since jack is bad at reporting:

He said this happened right when he got stage 2. This to me implies that the items are hidden, but something is causing them to unhide with the stage (likely they are staged) then once a relog happens, JEI applies after the staging does so its hidden again.

**Comment by JackRuby1** [comment] 2018-04-05 17:07
Because firstnecron complained I didn't explain how I did it... the only way I see how I get it was by going into age 2.

**Comment by justinrusso** [comment] 2018-05-23 04:46
This appears to be fixed in 3.0.7.

**Closed by justinrusso** 2018-05-23 04:46 UTC
Labels: Category: Staging, Investigate Further, Status: Completed, Type: Bug
