### ISSUE TITLE
Sevtech,  the latest hotfix version.

### ISSUE THREAD

**Issue by malloc1660** [DarkPacks/SevTech-Ages#4009] opened 2019-12-20 21:00 UTC
## Bug Report

but report: get nutrition maxed so you are receiving strength 1 buff.  Now go stand in effective range of totem pole with five wolf heads.  Verify you have strength 3.  Now leave area.  Strength 3 will remain, and be refreshed by the nutrition buff.  To remove strength 3 degrade health below nutrition buff levels.  Repeatable.  Kill slogoth in age 1 with three hits of spear.....lol

## Possible Solution

Probably related to the with AS potion combination thingy with max resistance 
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:submitted from phone sorry
* Crash Log:

## Client Information

* Modpack Version:LATEST
* Java Version:LATEST
* Launcher Used:multiMC
* Memory Allocated:6 gig
* Server/LAN/Single Player:single player
* Optifine Installed:yes
* Shaders Enabled:no

## World Information

* Modpack Version world created in:latest, new world

* Additional Content Installed:
None

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment] 2019-12-20 21:02
Duplicate of #3874

**Closed by sam-kirby** 2019-12-20 21:02 UTC
Labels: triage
