### ISSUE TITLE
Bronze tools use copper plates

### ISSUE THREAD

**Issue by elmatador316** [DarkPacks/SevTech-Ages#3072] opened 2018-07-08 21:07 UTC
Playing on 3.0.8

All the recipes for the bronze tools take copper plates, and there are not recipes for the copper tools.

Everything else is pretty self-explanitory...

**Comment by elmatador316** [comment] 2018-07-08 21:11
This is in age 2 BTW - not sure if the recipe changes in later ages

**Comment by Stifling-Bossness** [comment] 2018-07-09 00:00
Duplicate of #2802 please use the search function (and search in CLOSED issues as well)

**Closed** 2018-07-09 00:39 UTC
Labels: triage
