### ISSUE TITLE
Lost my progression when moving from single to multiplayer Support"

### ISSUE THREAD

**Issue by DjDjalilo** [DarkPacks/SevTech-Ages#3783] opened 2019-05-22 14:24 UTC
## Bug Report
Hi, recently i wanted to play with my brother (in lan) so i made a server and i juste replace the "world" folder by my saves in single player , but when i run the server and connect in, i lost all my progression (stuffs, quest...et ) and i play with the same accouny.

## Steps to Reproduce (for bugs)

1.Create a server
2.Start the server to generate a new world
3.Stop the server
4.Delete the "world" folder
5.Copy my old save in single player
6.Paste it on ly server folder
7.Rename it into "world"
8.Start the server
9.the cmd sad some entities missing and if i want to continue or not
10.i put the command : /fml confirm
11. the server succefully stared
12. i connect on the server
13. i lost all my progression but the block , item in chest , structure still there. 

## Logs

* Client/Server Log:
here missing entities log :

If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:entities:
    immcraft:immcraft_rock
Missing minecraft:soundevents:
    vc:record.storms
    galacticraftcore:entity.slime_death
    galacticraftcore:entity.bosslaugh
    galacticraftcore:ambience.singledrip
    vc:record.timescar
    galacticraftcore:entity.ooh
    galacticraftcore:player.openairlock
    galacticraftcore:player.closeairlock
    integrateddynamics:effect.page.flipsingle
    rftools:scan
    immcraft:pageturn
    galacticraftcore:galacticraft.music_space
    rftools:elevator_stop
    galacticraftcore:ambience.scaryscape
    vc:record.bramble
    galacticraftcore:player.parachute
    vc:record.jungle
    galacticraftcore:entity.astrominer
    vc:record.dire
    galacticraftcore:entity.bossdeath
    galacticraftcore:entity.ouch
    vc:record.castle
    galacticraftcore:shuttle.shuttle
    integrateddynamics:effect.page.flipmultiple
    galacticraftcore:block.deconstructor
    rftools:elevator_loop
    vc:sound.engineon
    rftools:elevator_start
* Crash Log:
## Client Information

* Modpack Version:3.1.1
* Java Version:8
* Launcher Used:AtLauncher
* Memory Allocated:8GB
* Server/LAN/Single Player:LAN (or server iam not sure...)
* Optifine Installed:No
* Shaders Enabled:No

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:8
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment] 2019-05-22 20:17
Duplicate of #3781 - is there a reason you're making a new issue?

**Closed** 2019-05-23 23:04 UTC
Labels: Duplicate
