### ISSUE TITLE
Age 1 waterwheel duplication

### ISSUE THREAD

**Issue by splinterdaz** [DarkPacks/SevTech-Ages#3214] opened 2018-08-02 18:52 UTC
Water wheel duplicates when the block is broken. Not a massive issue really but can make the game less challenging.

**Comment by artdude543** [comment] 2018-08-02 18:56
So you complain on Twitter? And then ignore the template? Just no.... Also...

Duplicate of #2971

**Closed by artdude543** 2018-08-02 18:56 UTC
Labels: triage

**Comment by splinterdaz** [comment] 2018-08-02 19:04
What the fuck is with that attitude.
