### ISSUE TITLE
Abyssalcraft Parrot summon not working in SMP

### ISSUE THREAD

**Issue by TakaNuva231** [DarkPacks/SevTech-Ages#1979] opened 2018-04-20 23:18 UTC
## Issue / Bug
Abyssalcraft parrot summoning ritual not summoning in SMP

## Expected Behavior
Instead of summoning a parrot after the ritual is complete nothing spawns and the materials are eaten by the ritual. Had more than the necessary amount of points in the necronomicon, and placed the materials in the appropriate positions.
## Possible Solution
Unsure of possible solution.

## Steps to Reproduce (for bugs)

1. On a server instance create an Abyssalcraft altar
2. Attempt to perform the Parrot Summoning ritual
3. Ritual should be accepted, however nothing will spawn and the materials will be used up.

## Context
As I could not find parrots in the jungles on the server I turned to Abyssalcraft. I was working to complete the advancement where you need to kill Baykok to get his bow. To do the totemic ritual you need an eagle bone whistle. I got the required materials, performed the Abyssalcraft ritual, however no parrot had spawned. I logged in and out of the server thinking it was desync and found that there was still no parrot. I performed the ritual again several times, I believe before I gave up I was at a total of 5 or 6 attempts, and still no parrots were spawning.

## Logs

* Client/Server Log:
[2018-04-19-1.log.gz](https://github.com/Darkosto/SevTech-Ages/files/1933889/2018-04-19-1.log.gz)

* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8.0.1710.11
* Launcher Used: Twitch Launcher

* Memory Allocated: 4.5GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 8.0.1710.11
* Operating System: Windows Server 16
* Hoster/Hosting Soultion: Private server
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by Jandakast** [comment] 2018-04-21 00:33
I cannot reproduce this in Dev. However, I'm curious what Biome you are in so I can ensure I'm testing it under the same circumstances.

**Comment by TakaNuva231** [comment] 2018-04-21 00:39
I'm not sure of the biome, as I am not far enough along the back to have that info. The best way to describe the biome is that has the same color of grass as Savannah and has large cobble boulders.

**Comment by CDArena** [comment] 2018-04-21 00:56
I havent tried the ritual myself, but do you also need something nearby to change into a parrot? (Just saying - the cedarwood sapling and buffalo rituals both did) The sapling ritual worked when I placed a bunch adjacent to the Base; and the Buffalo ritual worked when I dug a 2x2x2 pit right beside the Base to hold my cow.

I too found parrots in the Flat Savannah looking biomes (Acacia trees and yellowed looking grass), along a river with darklands on the other side. My parrot/savannah biome didn't have the boulders, but an adjacent mountain savannah biome does. Fed the parrot seeds, then after he landed on my shoulder I jumped to get him off, then right clicked to make him "sit" - somewhere in there I got the achievement.

**Comment by PsyberMind** [comment] 2018-04-21 16:11
Totemic Ceremonies need the Totem Base, The Abyssalcraft Rituals transform the objects on the pedestals into the desired object through the power of dark energy.. In this case, the feathers/eggs should have been enough to transform. I've tested this in a few biomes on my creative world, and haven't had any luck reproducing this myself.

**Closed** 2018-05-24 01:43 UTC
Labels: Status: Needs more Information
