### ISSUE TITLE
Bronze tools require copper plates

### ISSUE THREAD

**Issue by PleccyMM** [DarkPacks/SevTech-Ages#2882] opened 2018-06-14 15:03 UTC
## Bug Report
Bronze tools, such as swords, pickaxes etc, require copper plates instead of bronze plates. This is made even more apparent when the material used to repair these bronze tools is bronze ingots. Bronze armour however is fine and requires bronze plates.

## Expected Behaviour
It should require bronze plates instead of copper plates.

## Possible Solution
Change the crafting recipe to use bronze plates instead of copper.

## Steps to Reproduce (for bugs)

1. Go into JEI
2. Look at recipes for bronze tools

## Client Information
* Modpack Version: 3.08
* Launcher Used: AT Launcher
* Server/LAN/Single Player: Single Player
* Optifine Installed: False
* Shaders Enabled: False

## World Information
Modpack Version world created in: 3.08

**Comment by justinrusso** [comment] 2018-06-14 15:47
Duplicate of #2802

**Closed by justinrusso** 2018-06-14 15:47 UTC
Labels: Duplicate
