### ISSUE TITLE
Crash on Startup from Twitch

### ISSUE THREAD

**Issue by Jam3sDog** [DarkPacks/SevTech-Ages#3272] opened 2018-08-16 16:09 UTC
## Bug Report
crashes when loading modpacks

## Expected Behaviour
Run Normally

## Steps to Reproduce (for bugs)

1. launch game
2.wait

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/ANwT60w7

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-08-16 16:17
Duplicate of #3271

**Closed by artdude543** 2018-08-16 16:17 UTC
Labels: triage
