### ISSUE TITLE
Windsail/Hemp Cloth recipe in 3.0.4

### ISSUE THREAD

**Issue by IggyHitokage** [DarkPacks/SevTech-Ages#1360] opened 2018-04-03 18:37 UTC
## Issue / Bug

Windsail recipe has increased to incredibly difficult levels to create.

## Current Behavior

This save was created in 3.0.3 and upgraded to 3.0.4.

Windsail in 3.0.3 required 6 Hemp Cloth, which was made by 9 Hemp Fiber. In 3.0.4, it requires 48 Hemp Cloth and each Hemp Cloth requires 81 Hemp Fiber. Doing the math, that means that the basic windmill requires 15,552 Hemp Fiber, or 5,184 Hemp. This seems somewhat... limiting.

![2018-04-03_12 21 30](https://user-images.githubusercontent.com/38049501/38268529-8f269990-373b-11e8-839a-d3377a00092a.png)
![2018-04-03_12 21 34](https://user-images.githubusercontent.com/38049501/38268530-8f400844-373b-11e8-9024-73db5fffb024.png)
![2018-04-03_12 34 25](https://user-images.githubusercontent.com/38049501/38268531-8f5907cc-373b-11e8-9b68-6c6ae55c38e2.png)
![2018-04-03_12 34 37](https://user-images.githubusercontent.com/38049501/38268533-8f74c502-373b-11e8-9caa-9f598377c279.png)

## Possible Solution

Revert to 3.0.3 recipe. 

## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0_161
* Launcher Used:
* Resourcepack Enabled?: Persistence
* Optifine Installed?: No

**Comment by Amadeus99** [comment] 2018-04-03 21:52
Just an FYI, even though the recipes say they need stacks of 9 and 8, they actually only require one of each item in each position of the crafting table.  The recipes showing stacks of items is a bug for which I do not know the cause of.

**Comment by justinrusso** [comment] 2018-05-23 04:30
I believe this was fixed in a past version. Please create a new issue if the issue persists.

**Closed by justinrusso** 2018-05-23 04:30 UTC
Labels: Category: Recipe, Type: Request/Suggestion
