### ISSUE TITLE
Game hangs/freezes/crashes every 45 minutes or so.

### ISSUE THREAD

**Issue by AlleeCat2** [DarkPacks/SevTech-Ages#1677] opened 2018-04-10 02:35 UTC
## Issue / Bug
I've been playing this pack for a few days now, but I keep running into problem. No matter what my settings are, the game crashes every 45 minutes to an hour. I've gone for about an hour and a half at most and half an hour at least, but it usually averages about 45 minutes.

Doesn't matter what I'm doing. Doesn't matter what settings I'm using. Doesn't matter what I've got running in the background. The game freezes, goes to "not responding" status, and eventually I have to terminate the process. I even generated a new world to see if it was some kind of bug with the one I was playing on, but no, it couldn't be that simple.

I've included the most recent client logs, but I'm not sure how useful they are, since I looked through them to try to diagnose the problem myself, and there aren't any errors anywhere close to the crash. The log just ends when the game hangs. There don't seem to be crash logs, unless they're somehow stored in a completely different place than usual. I thought it might be a memory issue, but I've given it 6 GB and I still have the same problem.

## Expected Behavior
I doubt crashing every few minutes is a feature, rather than a bug, but if it is, I guess I'll shut up about it.

## Context
It's hard to provide context when it doesn't seem to matter at all what I'm doing when the game crashes. I could have been hanging out in the same area the entire time, or I could have never been in the same spot twice. I could have been constantly crafting or hardly ever opening my inventory. The only thing that seems to affect anything is the longer I play, the more likely it is I'll crash, and even that seems to be random (and yes, I've timed it.)

I normally wouldn't mind too much, since Minecraft is fairly good about autosaving so I don't lose much progress, but with a modpack of this size, loading up the game takes anywhere for 10 to 20 minutes, and most of that time my computer is virtually useless as FML will hog most of my CPU and RAM (I only have 8 GB, so giving it 6 is already a little close for comfort.) It's more frustrating than game-breaking, but it's basically ensuring that I play for, at most, two hours at a time before giving up and switching to something else.

## Logs
* Client/Server Log: https://gist.github.com/AlleeCat2/9410f92f71738155f4fce1b112c53172
* Crash Log: N/A (Doesn't seem to exist?)

## Client Information
* Modpack Version: 3.0.4
* Java Version:1.8.0_25
* Launcher Used: Twitch
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by SteseDav** [comment] 2018-04-10 07:06
3.0.6 is the current available version. You could consider backing up your saves and updating to the latest version.

**Comment by artdude543** [comment] 2018-04-10 13:32
Yeah can you update and see if the issue persists; a lot of mods has bugs/crashes in 3.0.4 so you may be fine in 3.0.6 :)

**Comment by daddy77gaming** [comment] 2018-04-10 15:52
Think others that use a 8gb machine should share their experiences..

Might help if you force twitch to use JAR launcher with latest java, as the native launcher uses an old java Version.

Also crashing every 45-60mins suggests some sort of memory leak where it takes that time to max out mem use and crash bc of that

**Comment by AlleeCat2** [comment] 2018-04-10 19:14
Well, it took me a while to get Twitch to actually update the game, but when I did, the problem seems to have gone away. At least partially. The game still hangs occasionally, but it usually starts working again after a about a minute, as opposed to before when it would hang indefinitely until I terminated it.

**Comment by FiveEYZ** [comment] 2018-04-10 22:43
If you don't like the suggested JAR launcher, then just add ```-version:1.8+``` to "Additional java arguments" and the Native launcher will use latest java currently installed.

**Comment by AlleeCat2** [comment] 2018-04-11 04:10
Looks like the problem didn't actually get fixed. I was able to play for a while last time, but suddenly after restarting, I'm getting the exact same problem. I'm going to mess with my Java settings and see if I can fix the issue at all. I have noticed that about 75% of the time I get the crash immediately after pressing the key to open my inventory. The other 25% I have no idea about.

**Comment by AlleeCat2** [comment] 2018-04-11 05:57
Yeah, I changed the Java version and this time, while I didn't get that error about IE manual crashes, I only made it about 20 minutes before the same thing happened as before. Not really sure what else to try besides starting to go and replace parts on my computer until something fixes it.

**Comment by AbdielKavash** [comment] 2018-04-11 12:46
Hi, I just want to let you know that you are not alone with this problem. I'm experiencing pretty much the same thing - between an hour or two of playing the game just hangs. No error message, just a "not responding", and I have to forcefully close the game.

There is no consistency between the freezes, it could happen when I open an inventory, it could be while getting mauled by zombies, or it could be while just walking around doing nothing in particular.

Playing with the latest modpack version (3.0.6), also latest Java version (8.161).

I have uploaded all my logs starting from when I installed the pack, hopefully they can be useful. The freezes have been happening consistently since the beginning. There are a bunch of exceptions being reported every once in a while, unfortunately I have no idea whether they are related.

[logs.zip](https://github.com/Darkosto/SevTech-Ages/files/1898815/logs.zip)

Here is DxDiag with my computer specs: https://pastebin.com/SBKiuEgd

**Comment by AlleeCat2** [comment] 2018-04-11 18:19
I looked over your specs and the only two things we have in common is 8GB of RAM and an NVIDIA graphics card. Otherwise our specs are completely different. I'm kind of at a loss for what could be causing this...

**Comment by SteseDav** [comment] 2018-04-13 02:43
may be worth checking your event log for corresponding disk errors?

**Comment by SteseDav** [comment] 2018-04-17 09:06
Thats interesting, and seems to confirm what others have been saying. It seems the advise is to only allocate no more than half of your available RAM to a modpack, otherwise MC gets confused.

**Comment by Yanislavcore** [comment] 2018-04-19 18:08
I have the same issue. In my case, the frequency of the crash is independent of the allocated memory (I usually play with 6GB of RAM and when set to less than 4GB, nothing changed).
My environment:
* Pack version: 3.0.6
* Launcher: ATLauncher 3.2.3.9
* JVM: OpenJDK 8 (1.8.0_162; 64-Bit Server VM (build 25.162-b12, mixed mode))
* OS: Ubuntu 16.04 (maybe it's important)
* Server/LAN/Single Player: SP
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by Yanislavcore** [comment] 2018-04-20 04:55
I have tested with Oracle JDK 8 and it has the same issue. 
I think all night about it, and now I have the idea, that the problem is with GC. Looks like complete garbage collection takes too long. Because of this, the GUI skips too many frames and therefore crashes. This can be seen in the last entries in my log.
I guess, that's why lowering the maximum memory helped the other guys. The smaller the heap, the faster the full garbage collection runs.

I will try to log GC actions or to connect with profiler and see what happens to the GC.
If this is really the cause of the problem, it can be solved by configuring the garbage collector to minimize GC pauses.

**Comment by SteseDav** [comment] 2018-05-03 07:47
Numorphan : - 10gb seems excessive in any case. Do you get the same issue if you allocate 6GB? does it happen sooner (which you'd expect)

**Comment by poxun1** [comment] 2018-05-06 10:31
I read in another thread that these freezes/crashes might be related to allocating more memory to Java than windows can spare combined with java GC... what happens is as java uses more memory it starts putting some of the unused (to be GC'd) Java memory into swapfile.  When Java later needs to GC all of that memory needs to be swapped back in before GC can complete causing the freezing.  Try slowly dropping the memory allocated to Java and/or close anything you don't need to be running to free memory....  Possibly having near full disks (especially SSD as it has to do its own form of GC as well at this point) supposedly can make this worse.  I'd suggest using window resource monitor to watch for a spike in hard faults.

**Comment by justinrusso** [comment] 2018-05-24 03:59
Does this issue still exist in 3.0.7? There were many changes including a handful of performance ones.

**Comment by Vjrcr** [comment] 2018-05-31 07:54
Yes? I think this is the same thing I'm getting where I can not interact with mobs and if I break a block I get nothing. A full game restart is need to fix it and it happen ever hour or so.

**Comment by Tahakk** [comment] 2018-06-25 11:46
Primal Core fixed this in their new update. See if it is still a problem for you.

**Comment by RobertLSnead** [comment] 2018-07-06 18:03
I keep getting a client crash and the server logs the following:
 [twilightforest]: Mod was keeping bauble items in reserve for player %s but they logged out! Items are being dropped.

**Comment by RobertLSnead** [comment] 2018-07-06 18:03
I'm on stage one!

**Comment by artdude543** [comment] 2018-08-10 18:57
Closing this as 3.1.0 has a tonne of perf fixes from many mods. If this is still an issue make a new issue with detailed information/logs etc...

**Closed by artdude543** 2018-08-10 18:57 UTC
Labels: Category: Performance, Status: Needs more Information, Type: Crash, Version: Outdated
