### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by maltssbm** [DarkPacks/SevTech-Ages#3281] opened 2018-08-16 17:49 UTC
## Bug Report

The game consistently crashes during stage 3/7 of launching the game. The game was working fine for the first few days that I've been playing it, and then I try to launch it today and this issue is happening every time.

## Steps to Reproduce (for bugs)

1. Launch the game from the Minecraft launcher.

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/U4dvtPu1

## Client Information

* Modpack Version: 3.0.8
* Java Version: 10.0.2
* Launcher Used: Twitch
* Memory Allocated: 6144 MB
* Server/LAN/Single Player: n/a
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-08-16 17:52
Duplicate of #3271

**Closed by artdude543** 2018-08-16 17:52 UTC
Labels: triage
