### ISSUE TITLE
Ironberry resistance stack invincibility

### ISSUE THREAD

**Issue by G3rrus** [DarkPacks/SevTech-Ages#4130] opened 2020-05-20 09:53 UTC
On 3.1.2 Hotfix 1 (Twitch Launcher)

## Expected Behaviour
Consuming Ironberries from Ironwood Trees will have the resistance buff stack with resistance buffs gained from having good nutrition resulting in invincibility. 

## Possible Solution
Don't allow for resistance stacks to the point of invincibility.

## Steps to Reproduce (for bugs)
- Have well enough nutrition for resistance buff to appear
- Consume Ironberry
- Try to take damage

**Comment by sam-kirby** [comment] 2020-05-20 13:45
Duplicate of #3874

**Closed by sam-kirby** 2020-05-20 13:45 UTC
Labels: triage

**Comment by G3rrus** [comment] 2020-05-20 14:28
This is not a duplicate. It is not the same issue and is absolutely unrelated to the hunting dimension.

**Comment by sam-kirby** [comment] 2020-05-20 14:59
This is absolutely a duplicate. The root cause of the issues is the same, namely the way Astral Sorcery calculates how potion effects should combine. In the current version it erroneously assumes that a lower level potion effect can extend a higher level effect, which is the issue you are describing - receiving a high level resistance effect from the ironberries and then a recurring low level effect from nutrition.

**Comment by sam-kirby** [comment] 2020-05-20 15:01
See HellFirePvP/AstralSorcery#1168 if you want more information.

**Comment by G3rrus** [comment] 2020-05-20 15:02
Right, Should've read through the end of the issue. My bad, thx for quick reply though :+1:
I assume its on the milestone for the next hotfix if there ever is one.
