### ISSUE TITLE
[3.0.7] Shoggoth's and Death

### ISSUE THREAD

**Issue by CorGaming** [DarkPacks/SevTech-Ages#2429] opened 2018-05-14 16:44 UTC
## Issue / Bug

 When a shoggoth kills you with his spit and you a death message saying "you got melted" or similar...when that particular type of kill happens you dont leave a grave behind...you literally melt the grave too...its super hard to kill shoggoth now because their spit has miles of range and it is like a machine gun that takes 3 hearts every hit even with bronze armor. Dont know if it happens every death because I dont die with other things...just shoggots which makes it super hard to get their flesh or gather 6 to make a monolith...they cant be trapped with any material (at age 1), unless you have monolith stone...they destroy every other block.

## Expected Behavior

I suppose you at least keep your grave to keep your itens, cause I already lost 2 full inventory thanks to that...maybe reduce their spit attack damage or frequency because as soon as they start it its impossible to get close or run.

## Possible Solution

Get the mod owner to reduce damage/frequency? Try to understand what makes that attack not leave a grave when it kills you.

## Steps to Reproduce (for bugs)

1. Find a Shoggoth
2. Let it spit you to death
3. Try to find your grave once you got dissolved by acid

## Context

I was trying to get 6 at once to get the monolith and after that I just tried to kill 1 by 1 to get flesh.

## Logs

* Client/Server Log: Its just a simple death + no grave, easy to test and the log I have shows that grave was created near (but in that case it doesnt).

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8
* Launcher Used: curse

* Memory Allocated: 4096Mb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by LordHellscream** [comment] 2018-05-14 23:47
I have to agree with OP, the shoggoth griefing is beyond reason with this new update (blaming the mob author here). Especially when hunting shoggoth is required very early in the game when little options are available to players. I would hate it to piss off a bunch of new players for this otherwise extremely additive and well-thought-out modpack.

**Comment by CorGaming** [comment] 2018-05-15 00:08
It pissed me off because I lost 2 full inventories and I dont know what was in both...I put myself in creative and gave back a few things I know I had, but things inside backpacks I didnt know so all lost unfortunately...and the freaking lair was like 2k blocks away from where I had my base so a lot of travel to find nothing x). They shoot things that do as much damage as the guardians, but like a machine gun...and with their goo its impossible to fight or run away :S. Besides the mob author changing/tunning it another solution could be rollback that mod...its impossible to gather 6 of them to get the monolith to spawn, and killing them requires a lot of patience...after my 3rd dead without killing any shoggoth (because yeah, they have a lot of hit points besides everything else), I just cheated their flesh to make the item required.

**Comment by ByteTemplar** [comment] 2018-05-15 11:16
You could just use Too Many Graves mods command to restore your latest grave. It can happen sometimes and thus that command exists.

/tmg_restore [playersname] latest

It is even possible to restore older ones.

**Comment by CorGaming** [comment] 2018-05-15 13:13
That I didnt know thanks :)...but no matter thats a bug because it happens all the time with the spit attack...and because shoggoth now are super hard to kill with the spit and the grief xD.

**Comment by justinrusso** [comment] 2018-05-15 13:33
Same situation as https://github.com/DarkPacks/SevTech-Ages/issues/1144

**Comment by kragnoth** [comment] 2018-05-15 13:48
Can the spit attack be disabled?  Because that sounds like a reasonable solution considering the original intent of the placement of shoggoth in the pack.  (horrible, but not super griefy)

**Comment by justinrusso** [comment] 2018-05-15 13:49
Why should the attack be disabled? The grave mod should just ... not delete itself?

**Comment by CorGaming** [comment] 2018-05-15 14:56
justinrusso, the spit attack is like a machine gun and gives 3 hearts of damage with bronze armor which is the most you can have in age 1...so its super impossible to kill a mob with 100hp, a lot of armor, with a crazy range attack xD. The bug is with the grave, sure, but the mob in 3.0.7 is super hard to kill for age 1 :S.

**Comment by Tozoz** [comment] 2018-05-23 19:07
This mod ruins the whole sevtech experience, got my grave destroyed by their acid, needs to be fixed.

**Comment by justinrusso** [comment] 2018-05-23 19:08
`/tmg_restore`

**Comment by NaturalHate** [comment] 2018-05-26 10:54
I wish I would have seen this before I went to attempt to go to a nearby lair.
Losing your entire inventory, especially my atlas with all my markers, kinda killed my interest in playing any more of this.

I find it pretty stupid that they deal so much damage as well, especially when there are like 10 of them in a lair who all just fire away at you. The spit attack also seem to destroy blocks, not sure if that's what happens or if there is no grave in the first place but this absolutely need to get nerfed.

**Comment by kragnoth** [comment] 2018-05-27 11:29
So... I see a fairly mediocre way of fixing this at least.  Set the config for block hardness against acid to be like 0.  That way all blocks are immune to being destroyed by shoggoth acid spit (theoretically, no idea what the hardness of the graves is)

Or the mod dev for tomb many graves (or one of you) could set the graves hardness to 3 and above.  That will make it immune to the spit as well.

**Comment by kevinsh7** [comment] 2018-05-31 04:40
It's like I'm playing a different game. I'm on version 3.0.6 single player. The lesser shoggoth don't spit acid for me - was this disabled then? The first two dens I found, I backed off a distance, build a "hidey hole" for the night, cached most of my gear and went to sleep. I then found the first lair empty, so I harvested all the monolith stone and figured that I could always trade with farmers for the shoggoth flesh if I really needed to. Then I found a second lair and confirmed it was alive and kicking. I backed off, created another "safe house", slept for the night, only to return to a dead lair - but it wasn't entirely empty. There were two frozen lesser shoggoth in the den. I don't even think they had collision shells, but maybe I could only walk through parts of them. So I restarted the game and they disappeared. So sleeping near a den will definitely kill them all off.

The third den I found - no sleeping! - was out in a river. I stayed in the water, they don't swim well, so I was able to kill a few. Then I rushed up to the entrance and placed down a "fence" of monolith blocks in columns on every other tile across the entrance. Then I learned they can climb. lol. So I finished caging them in and was able to farm as many as I needed.

So perhaps I have a different bug? In any case, does anyone know if any of the other dimensions have different distance ratios, like the 8 to 1 ratio of the nether? If so, that could really be useful. I'm in Age 2 now and need a blue middle gem for the furnace controller. Having a hard time finding swamps with druids, so being able to use the hunting dimension, or The Beneath for a portal network would really help with the exploration (assuming I can survive the plentiful mobs.)
@kevinsh7

**Comment by Targren** [comment] 2018-05-31 04:47
@kevinsh7 

>It's like I'm playing a different game. I'm on version 3.0.6 single player. 

The spitting mechanic didn't exist then.  The issue with the shuggoths disappearing should also have been fixed in the mod/pack update.

**Comment by justinrusso** [comment] 2018-05-31 13:08
@kevinsh7 please keep this on topic. Your entire issue is unrelated to the OP and seeks answers for things unrelated as well.

You are also on 3.0.6, not 3.0.7. Many of what you stated you're having issues with has been fixed.

**Comment by LordHellscream** [comment] 2018-06-04 23:45
it looks like setting hardiness to 0 doesn't seem to work based on someone in this thread:

https://github.com/Shinoow/AbyssalCraft/issues/286#issuecomment-394491101

**Comment by Yamza** [comment] 2018-07-09 12:13
Had this effect me last night as well. Was using a bauble bag to store all of my tools, walked into an HV cable, the Phoenix effect was activated and deleted all my baubles.

**Comment by monodemono** [comment] 2018-07-24 21:04
TombManyGraves has been replaced with Corail Tombstone, which fixes this issue.

**Closed by monodemono** 2018-07-24 21:04 UTC
Labels: Priority: Critical, Status: Reported To Mod, Type: Bug
