### ISSUE TITLE
Missing Water 

### ISSUE THREAD

**Issue by Crussell09** [DarkPacks/SevTech-Ages#3060] opened 2018-07-06 22:48 UTC
## Bug Report
Water is completely transparent whilst in a weedwood boat in the between lands making gen finding easy

## Expected Behaviour
water should be visible

## Possible Solution
most likely a graphical glitch that needs to be amended due to the camera being forced into 3rdperson

## Steps to Reproduce (for bugs)
when in a weedwood boat water will act as such but be completely invisible in the betweenlands

**Comment by Stifling-Bossness** [comment] 2018-07-07 03:05
Duplicate of #2506

**Closed** 2018-07-07 10:11 UTC
Labels: triage
