### ISSUE TITLE
Kinetic dynamo render error

### ISSUE THREAD

**Issue by Bagasl** [DarkPacks/SevTech-Ages#3257] opened 2018-08-12 18:24 UTC
## Bug Report
crash, when sb break kinetic dynamo near me

## Steps to Reproduce (for bugs)

1. place kinetic dynamo
2. break it

## Logs

* Client/Server Log:
* Crash Log: [crash-2018-08-12_21.09.57-client.txt](https://github.com/DarkPacks/SevTech-Ages/files/2281222/crash-2018-08-12_21.09.57-client.txt)

## Client Information

* Modpack Version: 3.0.8
* Java Version: 8
* Launcher Used:
* Memory Allocated: 6gb
* Server/LAN/Single Player: server
* Optifine Installed: yes
* Shaders Enabled: no

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version: 8
* Operating System: win10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by artdude543** [comment] 2018-08-12 18:34
So you still did this wrong. PasteBin/Gist your logs/reports. I'm not downloading files.... you're told in the template.

**Comment by artdude543** [comment] 2018-08-12 18:40
Duplicate of #3118

**Closed by artdude543** 2018-08-12 18:40 UTC
Labels: triage
