### ISSUE TITLE
Bone duplication.

### ISSUE THREAD

**Issue by Renari** [DarkPacks/SevTech-Ages#2725] opened 2018-06-02 18:19 UTC
## Bug Report

When repairing a sharp bone with a stack of bones in your crafting square, upon taking the sharp bone out of the result window the stack of bones quantity will double. 

## Expected Behaviour

One bone is taken and the durability repaired.

## Steps to Reproduce (for bugs)

1. ![](https://i.imgur.com/ses3Fj4.png)
2. ![](https://i.imgur.com/2cUIDMl.png)

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_172
* Launcher Used: Custom
* Memory Allocated: 4GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## Server Information
* Java Version: openjdk 1.8.0_171
* Operating System: Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
* Hoster/Hosting Solution: In House
* Sponge (Non-Vanilla Forge) Server: No
* Additional Content Installed: No

**Comment by artdude543** [comment] 2018-06-02 18:30
Duplicate of #2358

**Closed by artdude543** 2018-06-02 18:30 UTC
Labels: triage
