### ISSUE TITLE
No Crusher recipe for Platinum Cluster

### ISSUE THREAD

**Issue by Shananiganeer** [DarkPacks/SevTech-Ages#2771] opened 2018-06-06 14:48 UTC
## Bug Report

As the title suggests, Platinum Clusters cannot be processed by the IE Crusher, AA Crusher, nor Mekanism Crusher as there is no recipe for them. If you check JEI for recipes that make Platinum Dust the expected recipe in the IE Crusher has a blank input. https://imgur.com/3SDkhu0

## Expected Behaviour

There should be crusher recipes to convert ore:orePlatinum into 2x ore:dustPlatinum.

## Possible Solution

Could use CraftTweaker as a workaround to re-add the missing recipes. Whichever mod is unifying the oreDict may have screwed up the Crushers.

## Steps to Reproduce (for bugs)

1. Launch the pack and look in JEI for recipes that create Platinum Dust.
2. See that the only valid recipes in any of the Crushers are as secondary output from crushing Nickel.

## Logs

* Client/Server Log: https://gist.githubusercontent.com/Shananiganeer/ce4d0d5973f371fa5ad2b2518f208490/raw/0a5230536dc9a86ff754f56c15085cdff86eab88/gistfile1.txt
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_172
* Launcher Used: MultiMC
* Memory Allocated: 8GB
* Server/LAN/Single Player: SP and Server
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed: I removed BetterFoliage and FancyBlockParticles

**Comment by artdude543** [comment] 2018-06-06 15:43
Duplicate of #2315

**Closed by artdude543** 2018-06-06 15:43 UTC
Labels: triage
