### ISSUE TITLE
[Sevtech] Bronze shield casting problem

### ISSUE THREAD

**Issue by Nicolajsej123** [DarkPacks/SevTech-Ages#3836] opened 2019-07-11 12:40 UTC
## Bug Report
I'm pretty sure this is a bug but I have no idea how to fix it. I place my wooden shield in the casting table and click the faucet to let the 4 bronze ingots onto the shield. But when I right click it, only 6 mB comes out, and it tells me 1 ingot is consumed from the smelter, and If you click more it just consumes the rest, the same for porcelain and seared. But then when I put in more bronze, the ones that were put in the table magically comes back. I don't know how to fix this, if it's just bronze or is the casting just completely broken?

## Expected Behaviour
Metal should pour in and fill up around the wooden shield and create a bronze shield 
## Possible Solution
Use different metal

## Steps to Reproduce (for bugs)
1. Put wooden shield in the casting table
2. Melt the bronze
3. Right click the faucet

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.1
* Java Version: 211
* Launcher Used: AT launcher
* Memory Allocated: 10 gb
* Server/LAN/Single Player: Single
* Optifine Installed: nah
* Shaders Enabled: ye

## World Information
* Modpack Version world created in: 3.1.1

* Additional Content Installed:

**Comment by sk2048** [comment] 2019-07-11 12:44
Duplicate of #3650

**Closed by sk2048** 2019-07-11 12:44 UTC
Labels: triage
