### ISSUE TITLE
Celestial Altar Coal Engine not crafting

### ISSUE THREAD

**Issue by KoloXD** [DarkPacks/SevTech-Ages#3881] opened 2019-08-10 00:00 UTC
## Bug Report
The Coal Engine's crafting can not be started in the Celestial Altar in Age 2.

## Expected Behaviour
Being able to see the expected result of the recipe inserted in the altar and starting
the crafting

## Possible Solution
-

## Steps to Reproduce (for bugs)
Place every component of the engine into the altar.

## Logs
* Client/Server Log: -
* Crash Log: -

## Client Information

* Modpack Version: 3.0.8
* Java Version: 1.8.0_221
* Launcher Used: MultiMC 5
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.8
* Additional Content Installed: None

![Coal engine crafting 1](https://user-images.githubusercontent.com/29026973/62814653-2f5de980-bb12-11e9-987f-3afcd84f200a.png)

**Comment by sk2048** [comment] 2019-08-10 00:16
This definitely isn't an issue that's present generally as it's a required progression step in a version that's been out for over a year which has not previously been reported. 

The recipe used looks to be correct.

Have you made any changes to the pack at all? Mod updates for example?

If not, would you be able to upload `crafttweaker.log` from your server?

**Comment by KoloXD** [comment] 2019-08-10 00:22
We are using the modpack in its default state, no changes made. The host of the server is currently not available so it will take me some time to get that log. Your reply is much appreciated however.

**Comment by KoloXD** [comment] 2019-08-10 09:50
Here it is.
[crafttweaker.log](https://github.com/DarkPacks/SevTech-Ages/files/3488727/crafttweaker.log)

**Comment by sk2048** [comment] 2019-08-11 16:01
I can't see a reason this isn't working, what happens if you ignore the fact the result isn't showing and right click with the wand anyway?

**Comment by KoloXD** [comment] 2019-08-12 01:31
I have tried doing so, it does nothing. The 4 of us playing on the server are progressing in a team and pretty much I am leading in the unlocks. I have 3 sections unlocked in the astral tome, built the altar up to 127+ height, it has 4 relays around it properly as to exclude the possibility of it not having enough starlight. Checked the recipe multiple times, even put a screenshot of the recipe in jei side by side with the items im putting in the celestial altar.
I like to think I am decent at troubleshooting in things I am well versed in but this just eludes me.

**Comment by sk2048** [comment] 2019-08-12 01:56
Ah, it's the knowledge/research system then!

You unlock research in AS by building the altar. You need the chapter that tells you how to craft the next altar in order to use the current one. For this altar, you need the Constellation chapter.

Someone on your server may have it already, and if so they can use it. If not, then you can use commands to give yourself the research:

`/astralsorcery research @p CONSTELLATION`

**Comment by KoloXD** [comment] 2019-08-12 15:30
Thank you! Indeed that was the problem. I did not think that we have to progress in AS even more as the Celestial Altar was the one I could build in the Attunement research, nothing indicated that going further is required as the Constellation research contains entirely other blocks, unrelated to the Celestial Altar, only more recipes in it. However your help is much appreciated.

**Comment by sk2048** [comment] 2019-08-12 15:38
Okay, not a bug so marking as support - ignore the message from support bot as this is already solved :)

**Closed** 2019-08-12 15:38 UTC
Labels: Status: Cannot Reproduce, Type: Support, Version: Outdated
