### ISSUE TITLE
Sevtech Server Issue after updating to 3.0.7

### ISSUE THREAD

**Issue by FaytCloud** [DarkPacks/SevTech-Ages#2705] opened 2018-05-31 23:32 UTC
## Bug Report

Server unable to start after update to 3.0.7, starts and instantly stops
i have tried to reinstall the update

## Expected Behaviour

server starts and runs

## Possible Solution

no idea

## Steps to Reproduce (for bugs)

1. click on serverstart.bat

## Logs

* Client/Server Log:  https://gist.github.com/FaytCloud/7cfefa6a2ccd2688af5ec2b00480a31a
* Crash Log:  https://gist.github.com/FaytCloud/7cfefa6a2ccd2688af5ec2b00480a31a

## Client Information

* Modpack Version: 3.0.6 -3.0.7
* Java Version: 10.0.1
* Launcher Used: Twitch - Jar
* Memory Allocated: 4-8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 10.0.1
* Operating System: Win 10
* Hoster/Hosting Solution: Self Hosted
* Sponge (Non-Vanilla Forge) Server: Provided Server Files
* Additional Content Installed: No

**Comment by artdude543** [comment] 2018-06-01 18:34
Thank you for reporting an issue!

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

## Servers
For servers the process if farilt simple. Go the folder cotaining all the sever files/folder and you will see a folder called `crash-reports` follow the same process as above by getting the lastest one and uploading it to a text store.

**Comment by FaytCloud** [comment] 2018-06-01 22:34
no crash report generated

**Comment by artdude543** [comment] 2018-06-01 22:41
Then it's not a crash then.

**Comment by artdude543** [comment] 2018-06-01 22:47
So going through the logs. The server was stopped. Could be lack of memory or you closed it yourself. But the logs don't show any kind of error from the mods or the pack itself.

Not much I can offer as your already using our provided files. Which I assume you're using the StartScript provided.

But other than that I can't offer any other help. As there is nothing from the logs to essential _help_ with. Sorry.

**Closed by artdude543** 2018-06-01 22:47 UTC
Labels: Status: Needs more Information
