### ISSUE TITLE
Unable to join server after upgrading to 3.0.7

### ISSUE THREAD

**Issue by ShadowKing345** [DarkPacks/SevTech-Ages#2331] opened 2018-05-10 18:40 UTC
## Issue / Bug
The server starts fine but when a player joins they get a fatal error and the connection is terminated. When they attempt to rejoin they are stuck at the login screen.

## Expected Behavior

Player joins get disconnected. Attempts to join again gets stuck on the logging in... screen.

## Temporary Solution

Delete/Disable the Fancy Particles mod on both the server and the client. (Preferably disable the mod)

## Steps to Reproduce (for bugs)

1. Start a 3.0.6 world on a client (The world was at first a single player world).
2. Move world to server.
3. Upgrade server to 3.0.7 and accidentally delete the prestige folder.
4. Run /ftm confirm.
5. Log in, connection terminated.
6. Log in again and gets stuck on the logging in... screen.

## Logs 

* Client/Server Log:  Part 1: https://pastebin.com/62W2TvTV , Part 2: https://pastebin.com/Qu33Fnr0 , Part 3: https://pastebin.com/4nC2Am4Q (Do apologize for the multiple past bins. The log file was bigger then the limit)
* Crash Log: N\A

## Server Information
* Java Version: 1.8.0_162
* Operating System: Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-41-generic x86_64)
* Hoster/Hosting Solution: Local LAN Router (Using the port) 
* Sponge (Non-Vanilla Forge) Server?:No

* Additional Content Installed?:No

**Comment by greatmonkey** [comment] 2018-05-10 23:57
I just updated my single player world from 3.0.6 to 3.0.7 and now my game crashes to the launcher.  I know i log out in TW world in the ice biome.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.6-core.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 5/10/18 4:47 PM
Description: Colliding entity with block

java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/energy/wires/ImmersiveNetHandler
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.passive.AbstractHorse.func_191986_a(AbstractHorse.java:922)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.energy.wires.ImmersiveNetHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042)

-- Block being collided with --
Details:
	Block: minecraft:air
	Block location: World: (5,66,103), Chunk: (at 5,4,7 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1042)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:donkey (net.minecraft.entity.passive.EntityDonkey)
	Entity ID: 11
	Entity Name: Donkey
	Entity's Exact location: 6.60, 66.00, 103.87
	Entity's Block location: World: (6,66,103), Chunk: (at 6,4,7 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:963)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1949)
	at net.minecraft.entity.passive.AbstractHorse.func_191986_a(AbstractHorse.java:922)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2384)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:donkey (net.minecraft.entity.passive.EntityDonkey)
	Entity ID: 11
	Entity Name: Donkey
	Entity's Exact location: 6.60, 66.00, 103.87
	Entity's Block location: World: (6,66,103), Chunk: (at 6,4,7 in 0,6; contains blocks 0,0,96 to 15,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: A Whole New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -4022639232134189452
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (160,64,252), Chunk: (at 0,4,12 in 10,15; contains blocks 160,0,240 to 175,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7506245 game time, 6036302 day time
	Level dimension: 7
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 121856 (now: false), thunder time: 1375 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 648682864 bytes (618 MB) / 1979187200 bytes (1887 MB) up to 7874281472 bytes (7509 MB)
	JVM Flags: 4 total; -Xmx8448m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 2, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.3.2679 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                    | Signature                                |
	|:--------- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.3.2679.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2679 | forge-1.12.2-14.23.3.2679.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.176    | GalacticraftCore-1.12.2-4.0.1.176.jar     | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.176    | Galacticraft-Planets-1.12.2-4.0.1.176.jar | None                                     |
	| UCHIJAAAA | nutrition           | 3.0.0        | Nutrition-1.12.2-3.0.0.jar                | None                                     |
	| UCHIJAAAA | sev_tweaks_npc      | 0.0.3        | SevTweaksNPC-0.0.3.jar                    | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.176.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ShadowKing345** [comment] 2018-05-11 07:40
Quick update. I found out that if you revert back to 3.0.6 the server acts fine

**Comment by artdude543** [comment] 2018-05-11 14:01
@ShadowKing345 can you post the client logs when you were kicked? As the server won't log the error the client had to cause the disconnection. The logs posted are only the server ones.

**Comment by greatmonkey** [comment] 2018-05-11 20:19
so I got my world simi fix however when I went back to my base i found out that anything that was part of tinkers construct or astral sorcery was removed and half of my storage drawers turned into frames, any items that was in them are no longer a part of the world.  I am in stage 3 if that helps.

**Comment by SayulilyonPipeDream** [comment] 2018-05-12 03:15
Hello!

I am having this issue as well since I updated to 3.0.7 yesterday when I attempted to join our freshly updated server. As it stands, I'm the only one who is having this issue on our server.
The only thing I can think of is I had to remove ReAuth because it was crashing my Minecraft during it's load-up.
Anyway, here is the Error log pulled from the server when I try to connect: https://pastebin.com/D0wv0XaH

Thank you for your time!

**Comment by SayulilyonPipeDream** [comment] 2018-05-12 03:27
My client doesn't crash. All I get is this:
![sevtech error](https://user-images.githubusercontent.com/39207553/39953130-ad925b4e-5559-11e8-8490-24a52ebbc2d5.PNG)
Is there a way to pull up a log for the client without a crash?

**Comment by SayulilyonPipeDream** [comment] 2018-05-12 06:31
Ah! Found it!
[logs.zip](https://github.com/DarkPacks/SevTech-Ages/files/1997338/logs.zip)

**Comment by ShadowKing345** [comment] 2018-05-12 08:47
Here is my client log folder.
Also I found out that when start a new world you will get the intro screen and when you attempt to close that screen you get sent back to the home screen but the server still thinks you are in the game.
[logs.zip](https://github.com/DarkPacks/SevTech-Ages/files/1997422/logs.zip)

**Comment by artdude543** [comment] 2018-05-12 15:27
@SayulilyonPipeDream and @ShadowKing345  you seem to be missing libraries specifically Scala. What launcher are you using? Also, try disabling Fancy Particles and try to join it. (You will need to disable it on the server also for this test)

As both of you have the same issue with a lib missing Which the mod requires.

**Comment by ShadowKing345** [comment] 2018-05-12 15:51
@artdude543 I use the Twitch/Curse launcher to run minecraft.

**Comment by ShadowKing345** [comment] 2018-05-12 16:16
I can confirm that fancy particles is the cause of the player not being able to join the server.

**Comment by SayulilyonPipeDream** [comment] 2018-05-12 17:27
I can also confirm that the fancy block particle mod was causing trouble on my end. I had the server owner delete the mod as it wasn't enabled. Once I removed the client side mod, I was able to log in no problem.

I use the Twitch Launcher as well.

**Comment by artdude543** [comment] 2018-05-12 19:08
We confirmed the bug with the mod dev on this issue. Should be fixed in time but the way to fix it, for now, is to remove the mod. Thanks for checking guys!

**Closed** 2019-05-10 17:33 UTC
Labels: Status: Waiting on Mod Release, Type: Bug
