### ISSUE TITLE
Server crash when player is joining after upgrade to 3.0.7

### ISSUE THREAD

**Issue by haeihaeihaei** [DarkPacks/SevTech-Ages#2312] opened 2018-05-10 05:07 UTC
## Issue / Bug
The server starts fine, but when a player joins the server crash and generate an crashreport.

## Steps to Reproduce (for bugs)

Seems connected to our map so no idea how to reporoduce.

1. Start an 3.0.0 world (We started the world on 3.0.0)
2. Upgrade to 3.0.7
3. Run /fml confirm
4. Join server

## Logs
* Client/Server Log:
* Crash Log: https://pastebin.com/Ljz10pZU

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_162
* Launcher Used: Twitch

* Memory Allocated: 6096MB

* Server/LAN/Single Player: LAN
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 1.8.0_162
* Operating System: Ubuntu
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?: No

* Additional Content Installed?: No

**Comment by averoin** [comment] 2018-05-10 13:45
I am getting the same thing with the update. So I have went back to the prior version 3.0.6

**Comment by artdude543** [comment] 2018-05-10 16:02
This is a complicated issue as something in the world is ticking too much and/or is bugged. This has never been able to be resolved due to how complex it is and how many mods are playing with the timing with ticking and blocks.

To put it bluntly, the world is dead in essence when you try to use the newest version. This is _(generally speaking)_ caused from modded clients I.E. Extra mods installed which you then go over the Id limit which then other Id's are eaten over causing new issues. Once that damage is done that's it it's not reversible _(unless you had previous backups)_

Dropping down will technically fix your issue but then you breaking your ID mapping for the world and when you upgrade again you'll 60% chance of breaking the entire thing even worse. It's typically a bad idea to move up and down versions for modpacks due to new content/old content being removed and how the registry works for the game. We can't control that at all nor is it going to be fixed in 1.12 this situation would be more a thing in the past when 1.13 lands with fixes and changes to how the ID mapping works.

With you log Traverse seems to be a common theme with these crashes but not even the developers there has any idea of what's going on.

But TLDR; switching down version is a bad idea _(unless you used a backup w/o an upgrade)_ as you'll make your problem 100% worse. And to reiterate once you have done the damage to the ID mapping it's final. And there is nothing we can do to fix/change it. _(Easily that is)_

Unless someone can spend the time debugging this issue and find the mod(s) which are causing this issue then it won't ever have some kind of resolution. But the debugging would need to uncover proof and reproductions so this data can be passed on to the modders involved.

**Comment by averoin** [comment] 2018-05-10 16:49
@artdude543 I had made a backup before doing the update and used the backup when reverting back. I dont know that I can get my game to the new version so I shall play it out in the older version. I might try a few things later to see if I can get the new version to work if I do ill make a post here.

**Comment by Serria71** [comment] 2018-05-10 19:02
I'm having a very similar issue, its the same exception error except it seems more specific in my case: https://pastebin.com/ZrA8u6bs

**Comment by BonaireDreams** [comment] 2018-05-10 21:10
I fixed this when I moved to 3.0.6 by adding the mod Not enough ID's to the server. That fixed my exceeding ID challenge and allowed the world to load.

**Comment by haeihaeihaei** [comment] 2018-05-11 05:50
I had a backup before I upgraded to 3.0.7 as well, and it works well to run that world on 3.0.6. But I guess the easiest thing is to just create a new world and set the correct age for each player manually.

**Comment by WildLady99** [comment] 2018-05-11 21:43
Just for singleplayer I continuesly crashed when creating a world or trying to join one in 3.0.7 The only thing the report says is entity collision,
Time: 5/11/18 5:38 PM
Description: Colliding entity with block

**Comment by artdude543** [comment] 2018-05-12 14:08
@WildLady99 you'd need to link your crash report. That message is not helpful at all.

**Comment by artdude543** [comment] 2018-06-05 21:17
I'm going to close this one. It's an issue which is not easy to fix due to the complexity. 3.0.8 has a tonne of fixes so maybe it may be magically fixed? But this is out of our normal support scope for the pack.

Sorry.

**Closed by artdude543** 2018-06-05 21:17 UTC
Labels: Env: Server, Type: Crash
