### ISSUE TITLE
Mystical Agrictulture: Useless Silicon Essence

### ISSUE THREAD

**Issue by TheKedart** [DarkPacks/SevTech-Ages#3952] opened 2019-09-27 09:32 UTC
## Bug Report
Mystical Agriculture can grow Silicon plants, which give Silicon Essence. Silicon Essence does not have a recipe to convert it into actual Silicon (in fact, it has no recipes at all).

## Expected Behaviour
Expected to be able to craft Silicon Essence into Silicon.

## Possible Solution
Add recipe to craft Silicon out of Silicon Essence. Right now Silicon is non-renewable because of this issue! Alternatively (or additionally), add Silicon Ore to Void Ore Miner, possibly with Light Grey Laser Lens as bonus lens. The mod currently makes it extremely difficult to acquire silicon in age 5, which is when your AE2/RS operations start really ramping up and getting Silicon hungry.

## Client Information
* Modpack Version: 3.1.2 Hotfix 1

**Comment by sam-kirby** [comment] 2019-09-27 14:14
Duplicate of #3913 

Fixed for next release.

**Closed by sam-kirby** 2019-09-27 14:14 UTC
Labels: triage
