### ISSUE TITLE
Cyclic hydrator doesn't accept power/rf from immersive engineering.

### ISSUE THREAD

**Issue by pulli23** [DarkPacks/SevTech-Ages#3069] opened 2018-07-08 14:12 UTC
## Bug Report

Well as per title: the hydrator of cyclic doesn't accept any connection from immersive engineering, neither direct connectors nor a capacitor to any of its sides. (Nor connecting it to the top/bottom)

EDIT:
After placing/removing the capacitor half a dozen times it suddenly seems to draw power from the capacitor, though the interface at the cyclic hydrator doesn't change/doesn't show the power meter increasing.

## Expected Behaviour
Well i expect it to work directly when I place connector to a side of the hydrator. Especially since the convertor is age 4, yet the hydrator is age 3.

## Steps to Reproduce (for bugs)

1. place a hydrator, put the redstone mode to always on.
2. place a full capacitor to any side, place a connector to any side
3. In the interface of the hydrator you see the power doesn't raise.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.8
* Java Version: default from the native launcher.
* Launcher Used: twitch + native launcher.
* Memory Allocated: 4300+ MB 
* Server/LAN/Single Player: single player
* Optifine Installed: No (if it's not in the modpack)
* Shaders Enabled: None (other than default)

## World Information

* Modpack Version world created in: 3.0.7

* Additional Content Installed:

**Comment by artdude543** [comment] 2018-07-09 11:13
It does work but it has a visual bug which will be fixed in the next pack update. (Whenever that lands) but I can confirm it does work fine. You just don't know what power is stored/showing as using due to the visual glitch.

**Closed by artdude543** 2018-07-09 11:13 UTC
Labels: triage
