### ISSUE TITLE
[Recipe Error] Blood Magic BloodAltar not craftable

### ISSUE THREAD

**Issue by KS-HTK** [DarkPacks/SevTech-Ages#2500] opened 2018-05-17 20:41 UTC
## Issue / Bug
Age 1, a lot of Items from Blood Magic are not craftable.
This Includes: (Have not tested any others)
Blood Alter
Hellfire Forge

NEI shows the Recipe fine, but the Vanilla crafting table and crafting table on a stick do not show item output.
https://screenshot.net/gm3x6h5
The crafting table from age 0 doesn't work either. I do not have others to test with.

## Logs
* Client/Server Log: https://gist.github.com/KS-HTK/1dc6b1ac5ac9bb0d62f30b281db15aec

## Client Information
* Modpack Version: 3.0.7
* Java Version: 64Bit Java 8 (1.8.0_171)
* Launcher Used: ATLauncher
* Memory Allocated: 7 GB
* Server/LAN/Single Player: Opend to LAN for Commands
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by artdude543** [comment] 2018-05-17 21:08
Have you unlocked the stage correctly? And tried a reload? As there is no issue here. It's working for me and four streamers I'm currently watching.

**Comment by KS-HTK** [comment] 2018-05-18 01:45
The Bug/Issue is hard to trubleshoot. I can't tell if it has something to do with the unlocks, but I will test it. <-- Defnetly the advancements fault!

Well, it seems to be a wierd Bug.
There will be a Video what happend while testing a little more.

**Comment by KS-HTK** [comment] 2018-05-18 10:05
Here is a second Log of the Gameplay that solved the Issue:
https://gist.github.com/KS-HTK/d433375225882f11a289e7db0ddddc06

https://youtu.be/0rQDPnmrhNA

Steps to reproduce: Unknown.

**Comment by artdude543** [comment] 2018-05-18 10:26
No one could get this to be reproducible. Its worked since alpha. So I'm gonna close this on the basis of a rare case on your instance. Buts it's not an issues as of current.

**Closed** 2018-05-18 10:27 UTC
Labels: Status: Cannot Reproduce

**Comment by KS-HTK** [comment] 2018-05-22 09:28
I think it has to do with the savegame being renamed. I have renamed the savegame back to its original name and the bug seems to have vanished. Hard to test as it only appears if the age has not been discoverd on any savegame. Maybe recreateable with new instance, will test that later.
