### ISSUE TITLE
Portable Autocrafter causes crash upon use followed by recurring crash upon loading world

### ISSUE THREAD

**Issue by Hypersonic99** [DarkPacks/SevTech-Ages#2756] opened 2018-06-05 02:54 UTC
## Bug Report
Upon creating and attempting to use a portable autocrafter, my game crashed and I am unable to load the save without it crashing again. Specifically, I open the UI for it, entered the 2x2 sugarcane -> wicker recipe, set it to keep my inventory stocked with 4 wicker, and hit the autocraft button, and that's when it crashed.

## Expected Behaviour
I expected the autocrafter would continually craft sugarcane from my inventory into wicker up to the specified amount

## Possible Solution
I tried using an NBT editor to delete the item from my inventory, but it comes back every time I load the world. Please let me know if I need to do something other than delete the tag in my playerdata.

## Steps to Reproduce (for bugs)
1. Get a portable autocrafter
2. Open GUI
3. Put four sugarcane in upper right square
4. Up count to 4
5. Set to keep inventory stocked
6. Hit "Perform Autocrafting"
* I replicated this in a test world as well. Exact same result.

## Logs

* Crash Log:
[crash-2018-06-04_20.52.34-server.txt](https://github.com/DarkPacks/SevTech-Ages/files/2070646/crash-2018-06-04_20.52.34-server.txt)

## Client Information
* Modpack Version: 3.0.7
* Java Version: 8.0.1710.11
* Launcher Used: Twitch Launcher
* Memory Allocated: 6 gigs
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

## World Information
* Modpack Version world created in: 3.0.7

* Additional Content Installed: None

Please forgive me if I've made a mistake in formatting this post or if I need to provide any more info. I'm new to this website and very flustered over not being able to figure this out myself. Thanks in advance!

**Comment by artdude543** [comment] 2018-06-05 09:52
Duplicate of #2735

**Closed by artdude543** 2018-06-05 09:52 UTC
Labels: triage
