### ISSUE TITLE
Crafting leather with water from barrels doesn't seem to be working.

### ISSUE THREAD

**Issue by mmcmain** [DarkPacks/SevTech-Ages#2957] opened 2018-06-21 13:45 UTC
Reference issue:  https://github.com/DarkPacks/SevTech-Ages/issues/974

I can confirm that a full 1000mb bladder (at least from the tooltip it reports 1000mb) from a PrimalCore oak barrel filled with rain would not craft the hides in the stump. After emptying the bladder back into a barrel and filling it from the river it worked.

This is as of version 3.0.8.

**Comment by mmcmain** [comment] 2018-06-21 14:00
I think the bug might be related to the in-game tooltip and there is actually not 1000mb reported. If so, it is confusing because it definitely reports lower amounts (i.e. 144mb). But possibly it is rounding up when it gets close enough to 1000mb.

**Comment by artdude543** [comment] 2018-06-21 14:28
If you believe this is a tooltip issue. It would need reporting to the mod maker. But I've tested this now and did not encounter the same issue. Tested both on single and server to ensure for a valid test.

But also you did not follow the template enforced for the repo. So based on that and that I can't reproduce the issue. I'm going to close this issue to keep things fair. But again if you feel this is an issue with the mod please report back to them and tag this issue if you feel.

**Comment by artdude543** [comment] 2018-06-21 14:28
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SevTech-Ages/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Closed by artdude543** 2018-06-21 14:28 UTC
Labels: triage
