### ISSUE TITLE
SevTech Ages - Twitch - Game Crash on Launch.

### ISSUE THREAD

**Issue by mikez5565** [DarkPacks/SevTech-Ages#3283] opened 2018-08-16 17:59 UTC
## Bug Report

When Launching the mod via Twitch Launcher i get a crash.

The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

## Expected Behaviour

Normally the game would load as normal.

## Steps to Reproduce (for bugs)

1. Open up Twitch Launcher
2. Go to Mods - Minecraft - and then press play underneath SevTech Ages Version 3.0.8
3. once minecraft launcher loads up I click Play (forge-14.23.4.2707 - SevTech Ages)
4. After a while the game crashes with the message
      The game crashed whilst initializing game
      The game crashed whilst initializing game
      Error: java.lang.NullPointerException: Initializing game

5. the stage it crashes is in the below link (Screenshot)
[https://gyazo.com/33378d02f15e8a7710fb44f3b0be4b47](url)

## Logs

I tried updating Java after the error the first time in case that was the problem.

Java version 8 update 181 - https://pastebin.com/sEMzz7fa
Java version 10.0.2 - https://pastebin.com/6Zhjt0GT

## Client Information

* Windows Version: Windows 10
* Modpack Version: 3.0.8
* Java Version: 8u181 and 10.0.2
* Launcher Used: Twitch App
* Memory Allocated: 10GB
* Server/LAN/Single Player: Neither (crash prior to gameplay)
* Optifine Installed: no
* Shaders Enabled: no

## World Information

* Modpack Version world created in: irrelevant, crash before game launch.

* Additional Content Installed:

**Comment by artdude543** [comment] 2018-08-16 18:06
Duplicate of #3271

**Closed by artdude543** 2018-08-16 18:06 UTC
Labels: triage
