### ISSUE TITLE
Can't craft wooden axle with stage 2 recipe

### ISSUE THREAD

**Issue by AtomskPirateKing** [DarkPacks/SevTech-Ages#3968] opened 2019-10-12 16:55 UTC
## Expected Behaviour

Should be able to craft wooden axle with hemp rope and 2 wood moulding

## Steps to Reproduce (for bugs)

1.place Items in crafting gui
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.1.2 hotfix 1
* Java Version: 1.8.0.172 (64 bit)
* Launcher Used: Twitch Launcher
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single player
* Optifine Installed:no
* Shaders Enabled:no

## World Information

* Modpack Version world created in: I'm honestly not sure so this could be my issue it was probably the previous version as this is the first time i've seen an update option I could be wrong though.

* Additional Content Installed: None
image of bug in action:
[https://imgur.com/nOSj62j](url)

**Comment by sam-kirby** [comment] 2019-10-12 17:46
Duplicate of #3941 

See there for a solution.

**Closed by sam-kirby** 2019-10-12 17:46 UTC
Labels: Duplicate
