### ISSUE TITLE
Water wheel dupe

### ISSUE THREAD

**Issue by xtended2l** [DarkPacks/SevTech-Ages#3398] opened 2018-09-26 23:06 UTC
## Bug Report
Water Wheel duped when player breaks axle.

## Expected Behaviour
Receive one water wheel on removal.

## Steps to Reproduce (for bugs)
1. Place wooden gearbox, axle and water wheel on the axle.
2. Now break an axle.
3. You receive two water wheels instead of one.

**Comment by monodemono** [comment] 2018-09-27 04:14
Duplicate of #2971

Please use the search feature next time, this has been posted about a thousand times.

**Closed by monodemono** 2018-09-27 04:14 UTC
Labels: triage

**Comment by xtended2l** [comment] 2018-09-27 20:38
Can I ask you how? I tried several times, but I dont get where is search button?

**Comment by monodemono** [comment] 2018-09-28 04:08
<img width="2032" alt="screen shot 2018-09-27 at 21 06 19" src="https://user-images.githubusercontent.com/1161277/46187617-654b0400-c299-11e8-9244-d7698ec006a9.png">
