### ISSUE TITLE
Creative fluid tank can be crafted in a non-intended way

### ISSUE THREAD

**Issue by Giovanni-NL** [DarkPacks/SevTech-Ages#2719] opened 2018-06-02 10:48 UTC
## Bug Report

The creative fluid tank can be crafted in a way that should not be possible.

## Expected Behaviour

I don't expect this crafting recipe to be possible at all.

## Possible Solution

Fix the crafting recipe. This bug was probably introduced in 3.0.7 when it was made possible to clear a filled creative fluid tank by placing it in a crafting grid, and craft it into an empty creative tank.

## Steps to Reproduce (for bugs)

1. Place a Mekanism basic fluid tank in a crafting grid.
2. Extract the then crafted creative fluid tank from the crafting grid. 

## Logs

* Client/Server Log: n/a
* Crash Log: n/a

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0_171
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: 1.8.0_171
* Operating System: Linux
* Hoster/Hosting Solution: Private
* Sponge (Non-Vanilla Forge) Server: forge-1.12.2-14.23.3.2679
* Additional Content Installed: n/a

**Comment by artdude543** [comment] 2018-06-02 10:55
Duplicate of #2513

**Closed by artdude543** 2018-06-02 10:55 UTC
Labels: triage
