### ISSUE TITLE
SevTech Crash on Inistialization of Minecraft Phase 3

### ISSUE THREAD

**Issue by FatFreeBeefCake** [DarkPacks/SevTech-Ages#3282] opened 2018-08-16 17:59 UTC
https://pastebin.com/3sAjSuPV

I am having an issue as of today loading up Sevteech ages, I provided a link to the full crash report! any help would be great!

Here is another crash report as well! 

https://pastebin.com/9XsC1Ni2

**Comment by artdude543** [comment] 2018-08-16 18:06
Duplicate of #3271

**Closed by artdude543** 2018-08-16 18:06 UTC
Labels: triage
