### ISSUE TITLE
Server Crash when a player hits themselves with TiCon Shuriken.

### ISSUE THREAD

**Issue by JustHeyo** [DarkPacks/SevTech-Ages#2451] opened 2018-05-15 03:44 UTC
Multiplayer server crashed when an active player hit themselves with a Tinker's Construct Shuriken.

Steps to Reproduce (for bugs)
1 Make a Tinker's Construct Shuriken (This one was 1 bone, 1 cactus, 1 paper, 1 lavawood, in that order, then made indestructable via 5 Reinforced modifiers and had been leveled up once thereafter); 
2 get yourself into a large body of water and swim forward while underwater
3 throw a shuriken while continuing to swim forwards; note that the shuriken's movement will be slow and its flight will stall (due to the water) and then it will path straight downwards.
4 get hit by the falling shuriken.

Possible Solution
Resolve crash issue (sorry!) so that players can be struck by their own errant projectiles.

Client Information
Modpack Version: 3.0.7
Java Version: Java 8 update 171 64bit
Launcher Used: MultiMC 5
Memory Allocated: 7285MB total, 2632MB free
Server/LAN/Single Player: Server
Resourcepack Enabled?: No
Optifine Installed?: No

**Comment by JustHeyo** [comment] 2018-05-15 03:58
Server owner verified TiCon as the cause of the crash; logs requested.

**Comment by artdude543** [comment] 2018-05-15 10:14
You should not post an issue w/o the logs beforehand. This issue won't be looked into until the logs are posted.

**Comment by kragnoth** [comment] 2018-05-15 13:42
"This one was 1 bone, 1 cactus" that right there is the cause of the error.  Reflection damage coming back to the sender.  Probably infinitely cascading.  Please submit to TCon, as they have fixed similar issues fairly quickly in the past.  (with logs of course, those are super handy)

**Comment by ALongStringOfNumbers** [comment] 2018-05-16 19:13
There was a similar issue reported to Tinkers Construct that has already been fixed: https://github.com/SlimeKnights/TinkersConstruct/issues/3449

**Comment by artdude543** [comment] 2018-05-17 12:27
Closing as this issue was already fixed in the mod which we are using. And we don't have a crash log from the OP. So nothing we can do to help any further.

**Closed by artdude543** 2018-05-17 12:27 UTC
Labels: Status: Blocked, Status: Needs more Information
