### ISSUE TITLE
[Bug] Excavate Modifier is not craftable

### ISSUE THREAD

**Issue by Nagshell** [DarkPacks/SevTech-Ages#2543] opened 2018-05-20 12:14 UTC
## Issue / Bug
Excavate Modifier item shows in JEI, but is not craftable in crafting tables.

## Steps to Reproduce (for bugs)
I'm currently in age 3.
I took two screenshots, and did what I could between them.
I tried shift-clicking recipe from JEI, manually putting items.
I tried using vanilla crafting table and tinker crafting station.
Checked multiple versions of astral sorcery crystals / mazestone blocks.

## Logs
The only lines of log are those screenshots, nothing was logged in-between.
* Client/Server Log:
[14:03:51] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Saved screenshot as 2018-05-20_14.03.50.png
[14:06:32] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Saved screenshot as 2018-05-20_14.06.32.png

##Screenshot
https://imgur.com/a/xBTqfJw

## Client Information
* Modpack Version: 3.0.7
* Java Version: 1.8.0.171
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Single Player:
* Resourcepack Enabled?: No
* Optifine Installed?: No

* Additional Content Installed: 
AromaBackup-1.12.2-1.3.0.2.jar
Aroma1997Core-1.12.2-2.1.1.3.jar

**Comment by Stifling-Bossness** [comment] 2018-05-20 12:18
#2314

**Comment by Jandakast** [comment] 2018-05-20 14:55
Duplicate of #2314

**Closed by Jandakast** 2018-05-20 14:55 UTC
Labels: Duplicate

**Comment by ByteTemplar** [comment] 2018-05-20 15:15
You can fix this manually editing one line in script file (I did it and it works now), I don't know if its allowed to post info how to do it here though. 

If someone of the modpack devs can say this is allowed, I could post it.
