### ISSUE TITLE
Sevtech 3.0.8 crash on mod loading

### ISSUE THREAD

**Issue by hyperflair** [DarkPacks/SevTech-Ages#3278] opened 2018-08-16 17:15 UTC
## Bug Report

Sevtech Ages is crashing when loading in the mods.  Was able to play with no issues for a few weeks and it suddenly started crashing like this today.

## Expected Behaviour

When loading in the mods for the pack Minecraft will hang at some point and then crash.  The Minecraft launcher states the reason as:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

## Possible Solution

Already attempted repairing and reinstalling the mod pack through the Twitch launcher to no avail.  Not really sure what other options there are at this point as I have not had to deal with an issue like this before when using modpacks

## Steps to Reproduce (for bugs)

1. Open modpack via Twitch launcher
2. Launch modpack through Minecraft launcher window
3. Wait for crash to occur during loading of mods

## Logs

* Client/Server Log: https://pastebin.com/fX50Sbcc
* Crash Log: https://pastebin.com/X0J9t7ui

## Client Information

* Modpack Version: 3.0.8
* Java Version: version 8 Update 181 (build 1.8.0_181-b13)
* Launcher Used: Twitch Launcher
* Memory Allocated: 8,192 MB  ~8GB
* Server/LAN/Single Player: Server
* Optifine Installed: No (could not find in pack's mod list)
* Shaders Enabled: No

## World Information

* Modpack Version world created in: 3.0.8

* Additional Content Installed: No additional mods installed

**Comment by artdude543** [comment] 2018-08-16 17:19
Duplicate of #3271

**Closed by artdude543** 2018-08-16 17:19 UTC
Labels: triage

**Comment by hyperflair** [comment] 2018-08-16 17:28
Thanks for the redirect to the right page.
