### ISSUE TITLE
Game crash, rendering an item

### ISSUE THREAD

**Issue by xRavingBanana** [DarkPacks/SevTech-Ages#3117] opened 2018-07-17 12:26 UTC
## Bug Report
Game crashing when looking up the recipe for the stone grill.

## Expected Behaviour
When looking up the recipe for stone grill, it cycles through the different stone options, and crashes after getting to polished andesite

## Steps to Reproduce (for bugs)

1. Open inventory
2. type stone grill in JEI
3. Click stone grill to check recipe
4. Cycles through the different stone options and crashes on polished andesite

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/u3tWXAXu

## Client Information

* Modpack Version: 3.0.8
* Java Version: Version 8 Update 171
* Launcher Used: Twitch
* Memory Allocated: 8gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

## World Information

* Modpack Version world created in: Created in version 3.0.8

* Additional Content Installed: None

**Comment by artdude543** [comment] 2018-07-17 15:19
Duplicate of #3118

**Closed by artdude543** 2018-07-17 15:19 UTC
Labels: triage
