### ISSUE TITLE
Internal Server crash(updated)

### ISSUE THREAD

**Issue by Legatonin** [DarkPacks/SevTech-Ages#1989] opened 2018-04-21 08:57 UTC
## Issue / Bug
Every time i load in the world or go through dimension to dimension. It keeps on crashing and goes to the multiplayer screen.

## Expected Behavior
As what the issue does, i load in the world and it crashes. The same goes whenever i go through portals, it crashes as I get into the dimension.

## Possible Solution
That I do not know.

## Steps to Reproduce (for bugs)

1.Load in the world
2.Wait for a few seconds
3.Crashes
![screenshot_65](https://user-images.githubusercontent.com/28191018/39260400-f697dabe-48eb-11e8-8297-dc14616f97bc.png)

## Context
It's very annoying, especially when I'm recording for a video.

## Logs

* Client/Server Log:
* Crash Log: https://gist.github.com/Legatonin/a6c4619ed05cc6c2ae871178333774ea
Here should be the latest crash log i have in my folder.

## Client Information

* Modpack Version: Latest
* Java Version: jre1.8.0_161
* Launcher Used: Twitch

* Memory Allocated: 7680MB in Twitch Launcher settings

* Server/LAN/Single Player: single
* Resourcepack Enabled?: Cubic
* Optifine Installed?: yes

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by artdude543** [comment] 2018-04-21 11:10
Logs? You can't post an issue w/o any logs for your client. We're not magicians here.

Gist or Paste bin the latest logs from the client (or just after you "crash")

**Comment by Legatonin** [comment] 2018-04-21 17:50
@artdude543 Just added the logs.

**Comment by artdude543** [comment] 2018-04-24 21:54
You have uploaded the client log not the one I **need**. Please follow my guide below...

It appears you are logging an issue for a crash, but you have either not uploaded to PasteBin/Gist etc.. of the actual crash report. This report contains the needed data to help to locate the cause and a possible fix. To find the file needed please review the following for either of the launchers.

## Twitch
1. Select the SevTech Pack to view the modpack page.
2. Click the `...` button on the top right just next to `Get More Content`.
3. Click `Open Folder`.
4. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it. 

## ATLauncher
1. Select the Instances tab, then scroll to the instance of SevTech.
2. Click the bottom right button named `Open Folder`
3. This will then open the folder for the instance and you then will see the `crash-reports` folder in which that contains the needed file we need. Upload the latest to a service list above and comment with a link to it.

For any other launcher should be a similar process, if not consult with Google if you are not sure on how to find the folder. The information contained in these reports is critical for getting the crash fixed/looked into.

**Comment by Legatonin** [comment] 2018-04-25 16:13
@artdude543 Gotcha man, I'll get to it.

**Comment by Legatonin** [comment] 2018-04-25 16:28
@artdude543 Finished and found the crash report.

**Comment by justinrusso** [comment] 2018-05-24 03:46
This may be fixed with 3.0.7 changes. Please submit a new issue if the problem persists.

**Closed** 2018-05-24 03:45 UTC
Labels: Status: Needs more Information
