### ISSUE TITLE
Blood Magic Death No Graveyard

### ISSUE THREAD

**Issue by Voidfulqt** [DarkPacks/SevTech-Ages#2903] opened 2018-06-16 20:05 UTC
## Bug Report
 I got too trigger happy and killed myself , when I went back there was no grave, all my items are gone, the hard earned tinker's tools and bags filled with tools.

## Expected Behaviour
There should be a grave despite if you're accidentally killed yourself with the sacrificial dagger.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Stifling-Bossness** [comment] 2018-06-16 21:00
#2618 and please fill out the template completely next time

**Comment by artdude543** [comment] 2018-06-16 21:53
Duplicate of #2618

**Closed by artdude543** 2018-06-16 21:53 UTC
Labels: triage
