### ISSUE TITLE
Saw no longer works on Darklands Oak Log

### ISSUE THREAD

**Issue by EhGneissGuy** [DarkPacks/SevTech-Ages#2373] opened 2018-05-12 01:00 UTC
## Issue / Bug

Saw no longer works on darklands oak log.
![ezgif-1-2015dc1bd7](https://user-images.githubusercontent.com/17113297/39952057-45e55276-555e-11e8-9b22-c4bd0d489cb0.gif)

## Expected Behavior

Sawing darklands oak log should yield six planks and some sawdust.

## Possible Solution

Worked before update to 3.0.7.

## Steps to Reproduce (for bugs)

1. Try to saw darklands oak log.
2.

## Context

Cannot create darklands oak planks naturally.

## Logs

* Client/Server Log: https://gist.github.com/EhGneissGuy/a93aaddf29a5f24ed054a710f72f0466
* Crash Log: N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 8.171
* Launcher Used: Twitch

* Memory Allocated: 4GB

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: Yes
* Optifine Installed?: Yes

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Soultion: CubedHost 4Gb
* Sponge (Non-Vanilla Forge) Server?: N/A

* Additional Content Installed?:  Yes [Akashic Tome, Morph-o-Tool, Test Dummy Mod [MmmMmmMmmMmm])

**Comment by artdude543** [comment] 2018-05-12 03:15
Duplicate of #2369 same issue in general. (Being worked on)

**Closed by artdude543** 2018-05-12 03:15 UTC
