### ISSUE TITLE
Bronze hoe made out of copper

### ISSUE THREAD

**Issue by DeezHares** [DarkPacks/SevTech-Ages#3912] opened 2019-08-29 15:45 UTC
## Bug Report
so i was about to make a bronze hoe but i noticed that its made out of copper
wtf

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information

* Modpack Version world created in:

* Additional Content Installed:

**Comment by Stifling-Bossness** [comment] 2019-08-29 16:59
Duplicate of #3462, #3435, #3382, #3322, #3144, #3096, #3072, #3026, #2979, #2952, #2934, #2911, #2882, #2878, #2862, #2851, #2823, AND #2802. 

Please search for issues before making a new report, and make sure to fill out the template properly.

**Closed** 2019-08-29 19:35 UTC
Labels: triage
