### ISSUE TITLE
Auto crafters seem to not understand some recipes. (like cheese)

### ISSUE THREAD

**Issue by FyreDrop** [DarkPacks/SevTech-Ages#2729] opened 2018-06-03 05:51 UTC
## Bug Report
Current behavior: IE assembler and Inductive Logistics Automatic crafting table both seem to recognize the cheese recipe from actually additions, but will not craft it. 

IE Assembler will display the recipe, but greyed out as though there aren't the required ingredients, both with milk stored in the tank, and with an actual milk bucket. Functional when making sandstone though, so it's absolutely running recipes. 

IL Automatic crafter will "eat" the milk and egg, but won't output the product. This makes it act as though it's internal buffer is full and will refuse to craft anything else until broken and replaced.

## Expected Behavior

The auto crafters should be able to craft the recipes that they have a tooltip for and recognize the recipes of. 

## Possible Solution
N/A
## Steps to Reproduce (for bugs)

1.Have Immersive Engineering Assembler or Inductive Logistics Automatic Crafter
2.Insert ingredients for Actually Additions cheese

## Logs
N/A

## Client Information

* Modpack Version: 3.0.7
* Java Version: 1.8.0.25
* Launcher Used: Twitch app
* Memory Allocated: 9,472 MB
* Server/LAN/Single Player: Single Player/LAN
* Optifine Installed: No
* Shaders Enabled: No

**Comment by artdude543** [comment] 2018-06-03 08:59
Duplicate of #1803

Logistics Automatic crafting is also known but we still tag the other issue.

**Closed by artdude543** 2018-06-03 08:59 UTC
Labels: triage

**Comment by FyreDrop** [comment] 2018-06-03 10:05
Is it known that the handheld crafters from logistics will crash the client out and make the world un-joinable if you set it to craft one of these recipes? I just made this mistake...

**Comment by artdude543** [comment] 2018-06-03 10:37
New bug report with all the logs inc crash one.
