### ISSUE TITLE
Specific chunk causing inventories to go invisible

### ISSUE THREAD

**Issue by md5i** [DarkPacks/SevTech-Ages#3615] opened 2019-03-14 01:50 UTC
## Bug Report
After updating to 3.1.0, inventories in a specific chunk in my game are acting strangely.  A random amount of time after they are opened, (about 1-10 seconds), their inventories vanish.  They are still there, but are invisible.  Clicking a slot in the inventory restores it temporarily, as does closing and opening it again.  This is not visibly in vanilla chests, though.  However, a Tinkers' crafting station beside a vanilla chest that is in the affected chunk does display this problem, even if the crafting station is not in the same chunk.  Moreover, JEI doesn't see the inventory when it "vanishes" either, disallowing clicking in the recipe, as it doesn't see the necessary ingredients.  It works though, if you manage to click it in before they "vanish."

The chunk in question contains a Tinkers' smeltery and Pneumaticraft Air Compressor, UV light box, and Charging station.  I can see nothing else of particular interest.

## Expected Behaviour
Inventories don't vanish.

## Possible Solution
Moving inventories to a different chunk seems to be a viable workaround.

## Steps to Reproduce (for bugs)
This is in a local instance.  I'd be happy to make the world available.  I can put it on my local web server on request.

## Logs
Logs are available at: https://md5i.com/SevTechBug/logs

## World
World is available at: https://md5i.com/SevTechBug/world

## Client Information
* Modpack Version: 3.1.0
* Java Version: OpenJDK 64-Bit Server VM, version 1.8.0_191
* Launcher Used: MultiMC 5 - 0.6.5-1217
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: None

**Comment by Semi0ne** [comment] 2019-04-07 08:38
I'm having the same issue. After a little digging it seems to be a known issue between Tinkers' Construct Mod and Iron Chests Mod.

https://github.com/progwml6/ironchest/issues/162
https://github.com/SlimeKnights/TinkersConstruct/issues/3670

My solution will be to just not use any of the Iron Chests variants in the same chunk as the Smeltery. The Vanilla, Weedwood, PrimalChests and BiblioCraft chests don't have this issue for me.

**Comment by sk2048** [comment] 2019-06-12 13:25
Didn't catch this when it was posted, sorry. This will be handled as a duplicate of #3696 - despite coming first.

**Closed by sk2048** 2019-06-12 13:25 UTC
Labels: triage
