### ISSUE TITLE
Galacticraft machine not powering up 

### ISSUE THREAD

**Issue by daddy77gaming** [DarkPacks/SevTech-Ages#1530] opened 2018-04-06 23:18 UTC
![2018-04-07_00 16 49](https://user-images.githubusercontent.com/31905330/38448003-7e595ed6-3a01-11e8-9a08-c63adec81c59.png)
pipe shows power

![2018-04-07_00 16 33](https://user-images.githubusercontent.com/31905330/38448012-86809318-3a01-11e8-85ae-c074a7bbae7e.png)
machine does not take the power

https://github.com/Darkosto/SevTech-Ages/issues/1512

**Comment by artdude543** [comment] 2018-04-06 23:25
See my comment in the other issue and don't open up new ones! Just comment back to the old one.

**Comment by artdude543** [comment] 2018-04-06 23:47
Okay, this is a bug with Cyclic pipes being derpy somewhat. Using other mods power/fluid transfer works as intended.

**Comment by MJRLegends** [comment] 2018-04-12 15:14
Galacticraft should have Forge Energy support but theres a chance its bugged in 1.12.2, The best way to test if this is Cyclic or Galacticraft, would be to try another cable that uses Forge Energy Capability system as i believe this is what the Cyclic Energy cables support.

**Comment by Lewisking50** [comment] 2018-04-23 12:55
In age 4, I powered the oxygen collector with cyclic cables as well and we were very confused as to how to get the oxygen out of it and power it at the same time.
Turns out, you can "pour" oxygen gas into tanks with tinkers' construct faucets...

**Comment by Jandakast** [comment] 2018-05-23 21:56
Wonder if this is related to this https://github.com/PrinceOfAmber/Cyclic/issues/788

**Comment by artdude543** [comment] 2018-08-10 18:48
Will be resolved in 3.1.0 😄

**Closed by artdude543** 2018-08-10 18:48 UTC
Labels: Category: Mod, Status: Review Needed, Type: Bug
